# TCL File Generated by Component Editor 17.1
# Fri Nov 23 17:24:14 CET 2018
# DO NOT MODIFY


# 
# fir_subsystem "fir_subsystem" v2.0
#  2018.11.23.17:24:14
# 
# 

# 
# request TCL package from ACDS 16.1
# 
package require -exact qsys 16.1


# 
# module fir_subsystem
# 
set_module_property DESCRIPTION ""
set_module_property NAME fir_subsystem
set_module_property VERSION 2.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property AUTHOR ""
set_module_property DISPLAY_NAME fir_subsystem
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false
set_module_property REPORT_HIERARCHY false


# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL fir_subsystem_top
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property QUARTUS_SYNTH ENABLE_FILE_OVERWRITE_MODE false
add_fileset_file delay.sv SYSTEM_VERILOG PATH ../source/delay.sv
add_fileset_file fir_subcell.sv SYSTEM_VERILOG PATH ../source/fir_subcell.sv
add_fileset_file fir_subsystem_top.sv SYSTEM_VERILOG PATH ../source/fir_subsystem_top.sv TOP_LEVEL_FILE
add_fileset_file hard_limiter.sv SYSTEM_VERILOG PATH ../source/hard_limiter.sv
add_fileset_file iteration_ctrl.sv SYSTEM_VERILOG PATH ../source/iteration_ctrl.sv
add_fileset_file limits_fifo.v VERILOG PATH ../source/limits_fifo.v
add_fileset_file lvl_generator.sv SYSTEM_VERILOG PATH ../source/lvl_generator.sv
add_fileset_file output_ctrl.sv SYSTEM_VERILOG PATH ../source/output_ctrl.sv
add_fileset_file sample2lvl_converter.sv SYSTEM_VERILOG PATH ../source/sample2lvl_converter.sv
add_fileset_file sample_dispatcher.sv SYSTEM_VERILOG PATH ../source/sample_dispatcher.sv
add_fileset_file fir_filter.v VERILOG PATH ../source/fir_filter_ip/fir_filter.v
add_fileset_file altera_avalon_sc_fifo.v VERILOG PATH ../source/fir_filter_ip/fir_filter/altera_avalon_sc_fifo.v
add_fileset_file auk_dspip_avalon_streaming_controller_hpfir.vhd VHDL PATH ../source/fir_filter_ip/fir_filter/auk_dspip_avalon_streaming_controller_hpfir.vhd
add_fileset_file auk_dspip_avalon_streaming_sink_hpfir.vhd VHDL PATH ../source/fir_filter_ip/fir_filter/auk_dspip_avalon_streaming_sink_hpfir.vhd
add_fileset_file auk_dspip_avalon_streaming_source_hpfir.vhd VHDL PATH ../source/fir_filter_ip/fir_filter/auk_dspip_avalon_streaming_source_hpfir.vhd
add_fileset_file auk_dspip_lib_pkg_hpfir.vhd VHDL PATH ../source/fir_filter_ip/fir_filter/auk_dspip_lib_pkg_hpfir.vhd
add_fileset_file auk_dspip_math_pkg_hpfir.vhd VHDL PATH ../source/fir_filter_ip/fir_filter/auk_dspip_math_pkg_hpfir.vhd
add_fileset_file auk_dspip_roundsat_hpfir.vhd VHDL PATH ../source/fir_filter_ip/fir_filter/auk_dspip_roundsat_hpfir.vhd
add_fileset_file dspba_library.vhd VHDL PATH ../source/fir_filter_ip/fir_filter/dspba_library.vhd
add_fileset_file dspba_library_package.vhd VHDL PATH ../source/fir_filter_ip/fir_filter/dspba_library_package.vhd
add_fileset_file fir_filter_0002.vhd VHDL PATH ../source/fir_filter_ip/fir_filter/fir_filter_0002.vhd
add_fileset_file fir_filter_0002_ast.vhd VHDL PATH ../source/fir_filter_ip/fir_filter/fir_filter_0002_ast.vhd
add_fileset_file fir_filter_0002_rtl_core.vhd VHDL PATH ../source/fir_filter_ip/fir_filter/fir_filter_0002_rtl_core.vhd
add_fileset_file limits_fifo.qip OTHER PATH ../source/limits_fifo.qip
add_fileset_file fir_filter.qip OTHER PATH ../source/fir_filter_ip/fir_filter.qip
add_fileset_file register_file.sv SYSTEM_VERILOG PATH ../source/register_file.sv
add_fileset_file register_file_defs_pkg.sv SYSTEM_VERILOG PATH ../source/register_file_defs_pkg.sv

add_fileset SIM_VERILOG SIM_VERILOG "" ""
set_fileset_property SIM_VERILOG TOP_LEVEL fir_subsystem_top
set_fileset_property SIM_VERILOG ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property SIM_VERILOG ENABLE_FILE_OVERWRITE_MODE false
add_fileset_file fir_subsystem_top_tb.sv SYSTEM_VERILOG PATH ../source/fir_subsystem_top_tb.sv MENTOR_SPECIFIC
add_fileset_file delay.sv SYSTEM_VERILOG PATH ../source/delay.sv
add_fileset_file fir_subcell.sv SYSTEM_VERILOG PATH ../source/fir_subcell.sv
add_fileset_file fir_subsystem_top.sv SYSTEM_VERILOG PATH ../source/fir_subsystem_top.sv
add_fileset_file hard_limiter.sv SYSTEM_VERILOG PATH ../source/hard_limiter.sv
add_fileset_file iteration_ctrl.sv SYSTEM_VERILOG PATH ../source/iteration_ctrl.sv
add_fileset_file limits_fifo.v VERILOG PATH ../source/limits_fifo.v
add_fileset_file lvl_generator.sv SYSTEM_VERILOG PATH ../source/lvl_generator.sv
add_fileset_file output_ctrl.sv SYSTEM_VERILOG PATH ../source/output_ctrl.sv
add_fileset_file sample2lvl_converter.sv SYSTEM_VERILOG PATH ../source/sample2lvl_converter.sv
add_fileset_file sample_dispatcher.sv SYSTEM_VERILOG PATH ../source/sample_dispatcher.sv
add_fileset_file fir_filter.v VERILOG PATH ../source/fir_filter_ip/fir_filter.v
add_fileset_file altera_avalon_sc_fifo.v VERILOG PATH ../source/fir_filter_ip/fir_filter/altera_avalon_sc_fifo.v
add_fileset_file auk_dspip_avalon_streaming_controller_hpfir.vhd VHDL PATH ../source/fir_filter_ip/fir_filter/auk_dspip_avalon_streaming_controller_hpfir.vhd
add_fileset_file auk_dspip_avalon_streaming_sink_hpfir.vhd VHDL PATH ../source/fir_filter_ip/fir_filter/auk_dspip_avalon_streaming_sink_hpfir.vhd
add_fileset_file auk_dspip_avalon_streaming_source_hpfir.vhd VHDL PATH ../source/fir_filter_ip/fir_filter/auk_dspip_avalon_streaming_source_hpfir.vhd
add_fileset_file auk_dspip_lib_pkg_hpfir.vhd VHDL PATH ../source/fir_filter_ip/fir_filter/auk_dspip_lib_pkg_hpfir.vhd
add_fileset_file auk_dspip_math_pkg_hpfir.vhd VHDL PATH ../source/fir_filter_ip/fir_filter/auk_dspip_math_pkg_hpfir.vhd
add_fileset_file auk_dspip_roundsat_hpfir.vhd VHDL PATH ../source/fir_filter_ip/fir_filter/auk_dspip_roundsat_hpfir.vhd
add_fileset_file dspba_library.vhd VHDL PATH ../source/fir_filter_ip/fir_filter/dspba_library.vhd
add_fileset_file dspba_library_package.vhd VHDL PATH ../source/fir_filter_ip/fir_filter/dspba_library_package.vhd
add_fileset_file fir_filter_0002.vhd VHDL PATH ../source/fir_filter_ip/fir_filter/fir_filter_0002.vhd
add_fileset_file fir_filter_0002_ast.vhd VHDL PATH ../source/fir_filter_ip/fir_filter/fir_filter_0002_ast.vhd
add_fileset_file fir_filter_0002_rtl_core.vhd VHDL PATH ../source/fir_filter_ip/fir_filter/fir_filter_0002_rtl_core.vhd


# 
# parameters
# 
add_parameter FIR_TAPS_NUM INTEGER 63
set_parameter_property FIR_TAPS_NUM DEFAULT_VALUE 63
set_parameter_property FIR_TAPS_NUM DISPLAY_NAME FIR_TAPS_NUM
set_parameter_property FIR_TAPS_NUM TYPE INTEGER
set_parameter_property FIR_TAPS_NUM UNITS None
set_parameter_property FIR_TAPS_NUM ALLOWED_RANGES -2147483648:2147483647
set_parameter_property FIR_TAPS_NUM HDL_PARAMETER true
add_parameter MAX_SAMPLES_IN_RAM INTEGER 63
set_parameter_property MAX_SAMPLES_IN_RAM DEFAULT_VALUE 63
set_parameter_property MAX_SAMPLES_IN_RAM DISPLAY_NAME MAX_SAMPLES_IN_RAM
set_parameter_property MAX_SAMPLES_IN_RAM TYPE INTEGER
set_parameter_property MAX_SAMPLES_IN_RAM UNITS None
set_parameter_property MAX_SAMPLES_IN_RAM ALLOWED_RANGES -2147483648:2147483647
set_parameter_property MAX_SAMPLES_IN_RAM HDL_PARAMETER true
add_parameter MAX_LVLS_NUM INTEGER 32
set_parameter_property MAX_LVLS_NUM DEFAULT_VALUE 32
set_parameter_property MAX_LVLS_NUM DISPLAY_NAME MAX_LVLS_NUM
set_parameter_property MAX_LVLS_NUM TYPE INTEGER
set_parameter_property MAX_LVLS_NUM UNITS None
set_parameter_property MAX_LVLS_NUM HDL_PARAMETER true
add_parameter MAX_ITER_NUM INTEGER 1
set_parameter_property MAX_ITER_NUM DEFAULT_VALUE 1
set_parameter_property MAX_ITER_NUM DISPLAY_NAME MAX_ITER_NUM
set_parameter_property MAX_ITER_NUM TYPE INTEGER
set_parameter_property MAX_ITER_NUM UNITS None
set_parameter_property MAX_ITER_NUM HDL_PARAMETER true


# 
# display items
# 


# 
# connection point clock
# 
add_interface clock clock end
set_interface_property clock clockRate 0
set_interface_property clock ENABLED true
set_interface_property clock EXPORT_OF ""
set_interface_property clock PORT_NAME_MAP ""
set_interface_property clock CMSIS_SVD_VARIABLES ""
set_interface_property clock SVD_ADDRESS_GROUP ""

add_interface_port clock clock clk Input 1


# 
# connection point mm2st
# 
add_interface mm2st avalon_streaming end
set_interface_property mm2st associatedClock clock
set_interface_property mm2st associatedReset reset
set_interface_property mm2st dataBitsPerSymbol 16
set_interface_property mm2st errorDescriptor ""
set_interface_property mm2st firstSymbolInHighOrderBits true
set_interface_property mm2st maxChannel 0
set_interface_property mm2st readyLatency 0
set_interface_property mm2st ENABLED true
set_interface_property mm2st EXPORT_OF ""
set_interface_property mm2st PORT_NAME_MAP ""
set_interface_property mm2st CMSIS_SVD_VARIABLES ""
set_interface_property mm2st SVD_ADDRESS_GROUP ""

add_interface_port mm2st mm2st_data data Input 16
add_interface_port mm2st mm2st_valid valid Input 1
add_interface_port mm2st mm2st_ready ready Output 1


# 
# connection point reset
# 
add_interface reset reset end
set_interface_property reset associatedClock clock
set_interface_property reset synchronousEdges DEASSERT
set_interface_property reset ENABLED true
set_interface_property reset EXPORT_OF ""
set_interface_property reset PORT_NAME_MAP ""
set_interface_property reset CMSIS_SVD_VARIABLES ""
set_interface_property reset SVD_ADDRESS_GROUP ""

add_interface_port reset reset reset Input 1


# 
# connection point st2mm
# 
add_interface st2mm avalon_streaming start
set_interface_property st2mm associatedClock clock
set_interface_property st2mm associatedReset reset
set_interface_property st2mm dataBitsPerSymbol 16
set_interface_property st2mm errorDescriptor ""
set_interface_property st2mm firstSymbolInHighOrderBits true
set_interface_property st2mm maxChannel 0
set_interface_property st2mm readyLatency 0
set_interface_property st2mm ENABLED true
set_interface_property st2mm EXPORT_OF ""
set_interface_property st2mm PORT_NAME_MAP ""
set_interface_property st2mm CMSIS_SVD_VARIABLES ""
set_interface_property st2mm SVD_ADDRESS_GROUP ""

add_interface_port st2mm st2mm_data data Output 16
add_interface_port st2mm st2mm_valid valid Output 1
add_interface_port st2mm st2mm_ready ready Input 1


# 
# connection point csr
# 
add_interface csr avalon end
set_interface_property csr addressUnits WORDS
set_interface_property csr associatedClock clock
set_interface_property csr associatedReset reset
set_interface_property csr bitsPerSymbol 8
set_interface_property csr burstOnBurstBoundariesOnly false
set_interface_property csr burstcountUnits WORDS
set_interface_property csr explicitAddressSpan 0
set_interface_property csr holdTime 0
set_interface_property csr linewrapBursts false
set_interface_property csr maximumPendingReadTransactions 0
set_interface_property csr maximumPendingWriteTransactions 0
set_interface_property csr readLatency 0
set_interface_property csr readWaitTime 1
set_interface_property csr setupTime 0
set_interface_property csr timingUnits Cycles
set_interface_property csr writeWaitTime 0
set_interface_property csr ENABLED true
set_interface_property csr EXPORT_OF ""
set_interface_property csr PORT_NAME_MAP ""
set_interface_property csr CMSIS_SVD_VARIABLES ""
set_interface_property csr SVD_ADDRESS_GROUP ""

add_interface_port csr csr_address address Input 8
add_interface_port csr csr_byteenable byteenable Input 4
add_interface_port csr csr_read read Input 1
add_interface_port csr csr_readdata readdata Output 32
add_interface_port csr csr_write write Input 1
add_interface_port csr csr_writedata writedata Input 32
add_interface_port csr csr_waitrequest waitrequest Output 1
add_interface_port csr csr_response response Output 2
set_interface_assignment csr embeddedsw.configuration.isFlash 0
set_interface_assignment csr embeddedsw.configuration.isMemoryDevice 0
set_interface_assignment csr embeddedsw.configuration.isNonVolatileStorage 0
set_interface_assignment csr embeddedsw.configuration.isPrintableDevice 0

