# TCL File Generated by Component Editor 17.1
# Tue May 29 13:17:40 CEST 2018
# DO NOT MODIFY


# 
# limits_buffer "limits_buffer" v1.0
#  2018.05.29.13:17:40
# 
# 

# 
# request TCL package from ACDS 16.1
# 
package require -exact qsys 16.1


# 
# module limits_buffer
# 
set_module_property DESCRIPTION ""
set_module_property NAME limits_buffer
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property AUTHOR ""
set_module_property DISPLAY_NAME limits_buffer
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false
set_module_property REPORT_HIERARCHY false


# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL limits_buffer
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property QUARTUS_SYNTH ENABLE_FILE_OVERWRITE_MODE false
add_fileset_file limits_buffer.sv SYSTEM_VERILOG PATH ../source/limits_buffer.sv TOP_LEVEL_FILE

add_fileset SIM_VERILOG SIM_VERILOG "" ""
set_fileset_property SIM_VERILOG TOP_LEVEL limits_buffer
set_fileset_property SIM_VERILOG ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property SIM_VERILOG ENABLE_FILE_OVERWRITE_MODE false
add_fileset_file limits_buffer.sv SYSTEM_VERILOG PATH ../source/limits_buffer.sv MENTOR_SPECIFIC


# 
# parameters
# 


# 
# display items
# 


# 
# connection point clock
# 
add_interface clock clock end
set_interface_property clock clockRate 0
set_interface_property clock ENABLED true
set_interface_property clock EXPORT_OF ""
set_interface_property clock PORT_NAME_MAP ""
set_interface_property clock CMSIS_SVD_VARIABLES ""
set_interface_property clock SVD_ADDRESS_GROUP ""

add_interface_port clock clock clk Input 1


# 
# connection point reset
# 
add_interface reset reset end
set_interface_property reset associatedClock clock
set_interface_property reset synchronousEdges DEASSERT
set_interface_property reset ENABLED true
set_interface_property reset EXPORT_OF ""
set_interface_property reset PORT_NAME_MAP ""
set_interface_property reset CMSIS_SVD_VARIABLES ""
set_interface_property reset SVD_ADDRESS_GROUP ""

add_interface_port reset reset reset Input 1


# 
# connection point port_a
# 
add_interface port_a avalon end
set_interface_property port_a addressUnits WORDS
set_interface_property port_a associatedClock clock
set_interface_property port_a associatedReset reset
set_interface_property port_a bitsPerSymbol 8
set_interface_property port_a burstOnBurstBoundariesOnly false
set_interface_property port_a burstcountUnits WORDS
set_interface_property port_a explicitAddressSpan 0
set_interface_property port_a holdTime 0
set_interface_property port_a linewrapBursts false
set_interface_property port_a maximumPendingReadTransactions 0
set_interface_property port_a maximumPendingWriteTransactions 0
set_interface_property port_a readLatency 0
set_interface_property port_a readWaitTime 1
set_interface_property port_a setupTime 0
set_interface_property port_a timingUnits Cycles
set_interface_property port_a writeWaitTime 0
set_interface_property port_a ENABLED true
set_interface_property port_a EXPORT_OF ""
set_interface_property port_a PORT_NAME_MAP ""
set_interface_property port_a CMSIS_SVD_VARIABLES ""
set_interface_property port_a SVD_ADDRESS_GROUP ""

add_interface_port port_a port_a_address address Input 8
add_interface_port port_a port_a_chipselect chipselect Input 1
add_interface_port port_a port_a_read read Input 1
add_interface_port port_a port_a_readdata readdata Output 32
add_interface_port port_a port_a_write write Input 1
add_interface_port port_a port_a_writedata writedata Input 32
add_interface_port port_a port_a_byteenable byteenable Input 4
add_interface_port port_a port_a_waitrequest waitrequest Output 1
set_interface_assignment port_a embeddedsw.configuration.isFlash 0
set_interface_assignment port_a embeddedsw.configuration.isMemoryDevice 0
set_interface_assignment port_a embeddedsw.configuration.isNonVolatileStorage 0
set_interface_assignment port_a embeddedsw.configuration.isPrintableDevice 0


# 
# connection point port_b
# 
add_interface port_b avalon end
set_interface_property port_b addressUnits WORDS
set_interface_property port_b associatedClock clock
set_interface_property port_b associatedReset reset
set_interface_property port_b bitsPerSymbol 8
set_interface_property port_b burstOnBurstBoundariesOnly false
set_interface_property port_b burstcountUnits WORDS
set_interface_property port_b explicitAddressSpan 0
set_interface_property port_b holdTime 0
set_interface_property port_b linewrapBursts false
set_interface_property port_b maximumPendingReadTransactions 0
set_interface_property port_b maximumPendingWriteTransactions 0
set_interface_property port_b readLatency 0
set_interface_property port_b readWaitTime 1
set_interface_property port_b setupTime 0
set_interface_property port_b timingUnits Cycles
set_interface_property port_b writeWaitTime 0
set_interface_property port_b ENABLED true
set_interface_property port_b EXPORT_OF ""
set_interface_property port_b PORT_NAME_MAP ""
set_interface_property port_b CMSIS_SVD_VARIABLES ""
set_interface_property port_b SVD_ADDRESS_GROUP ""

add_interface_port port_b port_b_address address Input 8
add_interface_port port_b port_b_chipselect chipselect Input 1
add_interface_port port_b port_b_read read Input 1
add_interface_port port_b port_b_readdata readdata Output 32
add_interface_port port_b port_b_write write Input 1
add_interface_port port_b port_b_writedata writedata Input 32
add_interface_port port_b port_b_byteenable byteenable Input 4
add_interface_port port_b port_b_waitrequest waitrequest Output 1
set_interface_assignment port_b embeddedsw.configuration.isFlash 0
set_interface_assignment port_b embeddedsw.configuration.isMemoryDevice 0
set_interface_assignment port_b embeddedsw.configuration.isNonVolatileStorage 0
set_interface_assignment port_b embeddedsw.configuration.isPrintableDevice 0

