# TCL File Generated by Component Editor 17.1
# Mon Jun 04 11:45:12 CEST 2018
# DO NOT MODIFY


# 
# output_ctrl "output_ctrl" v1.0
#  2018.06.04.11:45:12
# 
# 

# 
# request TCL package from ACDS 16.1
# 
package require -exact qsys 16.1


# 
# module output_ctrl
# 
set_module_property DESCRIPTION ""
set_module_property NAME output_ctrl
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property AUTHOR ""
set_module_property DISPLAY_NAME output_ctrl
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false
set_module_property REPORT_HIERARCHY false


# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL output_ctrl
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property QUARTUS_SYNTH ENABLE_FILE_OVERWRITE_MODE false
add_fileset_file output_ctrl.sv SYSTEM_VERILOG PATH ../source/output_ctrl.sv TOP_LEVEL_FILE

add_fileset SIM_VERILOG SIM_VERILOG "" ""
set_fileset_property SIM_VERILOG TOP_LEVEL output_ctrl
set_fileset_property SIM_VERILOG ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property SIM_VERILOG ENABLE_FILE_OVERWRITE_MODE true
add_fileset_file output_ctrl.sv SYSTEM_VERILOG PATH ../source/output_ctrl.sv MENTOR_SPECIFIC


# 
# parameters
# 
add_parameter USE_COMB_LOGIC INTEGER 0
set_parameter_property USE_COMB_LOGIC DEFAULT_VALUE 0
set_parameter_property USE_COMB_LOGIC DISPLAY_NAME USE_COMB_LOGIC
set_parameter_property USE_COMB_LOGIC TYPE INTEGER
set_parameter_property USE_COMB_LOGIC UNITS None
set_parameter_property USE_COMB_LOGIC ALLOWED_RANGES -2147483648:2147483647
set_parameter_property USE_COMB_LOGIC HDL_PARAMETER true


# 
# display items
# 


# 
# connection point clock
# 
add_interface clock clock end
set_interface_property clock clockRate 0
set_interface_property clock ENABLED true
set_interface_property clock EXPORT_OF ""
set_interface_property clock PORT_NAME_MAP ""
set_interface_property clock CMSIS_SVD_VARIABLES ""
set_interface_property clock SVD_ADDRESS_GROUP ""

add_interface_port clock clock clk Input 1


# 
# connection point reset
# 
add_interface reset reset end
set_interface_property reset associatedClock clock
set_interface_property reset synchronousEdges DEASSERT
set_interface_property reset ENABLED true
set_interface_property reset EXPORT_OF ""
set_interface_property reset PORT_NAME_MAP ""
set_interface_property reset CMSIS_SVD_VARIABLES ""
set_interface_property reset SVD_ADDRESS_GROUP ""

add_interface_port reset reset reset Input 1


# 
# connection point limiter
# 
add_interface limiter avalon_streaming end
set_interface_property limiter associatedClock clock
set_interface_property limiter associatedReset reset
set_interface_property limiter dataBitsPerSymbol 16
set_interface_property limiter errorDescriptor ""
set_interface_property limiter firstSymbolInHighOrderBits true
set_interface_property limiter maxChannel 0
set_interface_property limiter readyLatency 0
set_interface_property limiter ENABLED true
set_interface_property limiter EXPORT_OF ""
set_interface_property limiter PORT_NAME_MAP ""
set_interface_property limiter CMSIS_SVD_VARIABLES ""
set_interface_property limiter SVD_ADDRESS_GROUP ""

add_interface_port limiter limiter_data data Input 16
add_interface_port limiter limiter_ready ready Output 1
add_interface_port limiter limiter_valid valid Input 1


# 
# connection point out
# 
add_interface out avalon_streaming start
set_interface_property out associatedClock clock
set_interface_property out associatedReset reset
set_interface_property out dataBitsPerSymbol 16
set_interface_property out errorDescriptor ""
set_interface_property out firstSymbolInHighOrderBits true
set_interface_property out maxChannel 0
set_interface_property out readyLatency 0
set_interface_property out ENABLED true
set_interface_property out EXPORT_OF ""
set_interface_property out PORT_NAME_MAP ""
set_interface_property out CMSIS_SVD_VARIABLES ""
set_interface_property out SVD_ADDRESS_GROUP ""

add_interface_port out out_data data Output 16
add_interface_port out out_ready ready Input 1
add_interface_port out out_valid valid Output 1


# 
# connection point iter
# 
add_interface iter conduit end
set_interface_property iter associatedClock clock
set_interface_property iter associatedReset reset
set_interface_property iter ENABLED true
set_interface_property iter EXPORT_OF ""
set_interface_property iter PORT_NAME_MAP ""
set_interface_property iter CMSIS_SVD_VARIABLES ""
set_interface_property iter SVD_ADDRESS_GROUP ""

add_interface_port iter iter_output_enable new_signal Input 1
add_interface_port iter iter_ready new_signal_1 Output 1

