// soc_system_mm_interconnect_2.v

// This file was auto-generated from altera_mm_interconnect_hw.tcl.  If you edit it your changes
// will probably be lost.
// 
// Generated using ACDS version 16.1 196

`timescale 1 ps / 1 ps
module soc_system_mm_interconnect_2 (
		input  wire        clk_0_clk_clk,                                            //                                          clk_0_clk.clk
		input  wire        sample2lvl_converter_0_reset_reset_bridge_in_reset_reset, // sample2lvl_converter_0_reset_reset_bridge_in_reset.reset
		input  wire [9:0]  sample2lvl_converter_0_ram_address,                       //                         sample2lvl_converter_0_ram.address
		output wire        sample2lvl_converter_0_ram_waitrequest,                   //                                                   .waitrequest
		input  wire [1:0]  sample2lvl_converter_0_ram_byteenable,                    //                                                   .byteenable
		input  wire        sample2lvl_converter_0_ram_chipselect,                    //                                                   .chipselect
		input  wire        sample2lvl_converter_0_ram_read,                          //                                                   .read
		output wire [15:0] sample2lvl_converter_0_ram_readdata,                      //                                                   .readdata
		input  wire        sample2lvl_converter_0_ram_write,                         //                                                   .write
		input  wire [15:0] sample2lvl_converter_0_ram_writedata,                     //                                                   .writedata
		output wire [8:0]  sample_buffer_s1_address,                                 //                                   sample_buffer_s1.address
		output wire        sample_buffer_s1_write,                                   //                                                   .write
		input  wire [15:0] sample_buffer_s1_readdata,                                //                                                   .readdata
		output wire [15:0] sample_buffer_s1_writedata,                               //                                                   .writedata
		output wire [1:0]  sample_buffer_s1_byteenable,                              //                                                   .byteenable
		output wire        sample_buffer_s1_chipselect,                              //                                                   .chipselect
		output wire        sample_buffer_s1_clken                                    //                                                   .clken
	);

	wire         sample2lvl_converter_0_ram_translator_avalon_universal_master_0_waitrequest;   // sample_buffer_s1_translator:uav_waitrequest -> sample2lvl_converter_0_ram_translator:uav_waitrequest
	wire  [15:0] sample2lvl_converter_0_ram_translator_avalon_universal_master_0_readdata;      // sample_buffer_s1_translator:uav_readdata -> sample2lvl_converter_0_ram_translator:uav_readdata
	wire         sample2lvl_converter_0_ram_translator_avalon_universal_master_0_debugaccess;   // sample2lvl_converter_0_ram_translator:uav_debugaccess -> sample_buffer_s1_translator:uav_debugaccess
	wire   [9:0] sample2lvl_converter_0_ram_translator_avalon_universal_master_0_address;       // sample2lvl_converter_0_ram_translator:uav_address -> sample_buffer_s1_translator:uav_address
	wire         sample2lvl_converter_0_ram_translator_avalon_universal_master_0_read;          // sample2lvl_converter_0_ram_translator:uav_read -> sample_buffer_s1_translator:uav_read
	wire   [1:0] sample2lvl_converter_0_ram_translator_avalon_universal_master_0_byteenable;    // sample2lvl_converter_0_ram_translator:uav_byteenable -> sample_buffer_s1_translator:uav_byteenable
	wire         sample2lvl_converter_0_ram_translator_avalon_universal_master_0_readdatavalid; // sample_buffer_s1_translator:uav_readdatavalid -> sample2lvl_converter_0_ram_translator:uav_readdatavalid
	wire         sample2lvl_converter_0_ram_translator_avalon_universal_master_0_lock;          // sample2lvl_converter_0_ram_translator:uav_lock -> sample_buffer_s1_translator:uav_lock
	wire         sample2lvl_converter_0_ram_translator_avalon_universal_master_0_write;         // sample2lvl_converter_0_ram_translator:uav_write -> sample_buffer_s1_translator:uav_write
	wire  [15:0] sample2lvl_converter_0_ram_translator_avalon_universal_master_0_writedata;     // sample2lvl_converter_0_ram_translator:uav_writedata -> sample_buffer_s1_translator:uav_writedata
	wire   [1:0] sample2lvl_converter_0_ram_translator_avalon_universal_master_0_burstcount;    // sample2lvl_converter_0_ram_translator:uav_burstcount -> sample_buffer_s1_translator:uav_burstcount

	altera_merlin_master_translator #(
		.AV_ADDRESS_W                (10),
		.AV_DATA_W                   (16),
		.AV_BURSTCOUNT_W             (1),
		.AV_BYTEENABLE_W             (2),
		.UAV_ADDRESS_W               (10),
		.UAV_BURSTCOUNT_W            (2),
		.USE_READ                    (1),
		.USE_WRITE                   (1),
		.USE_BEGINBURSTTRANSFER      (0),
		.USE_BEGINTRANSFER           (0),
		.USE_CHIPSELECT              (1),
		.USE_BURSTCOUNT              (0),
		.USE_READDATAVALID           (0),
		.USE_WAITREQUEST             (1),
		.USE_READRESPONSE            (0),
		.USE_WRITERESPONSE           (0),
		.AV_SYMBOLS_PER_WORD         (2),
		.AV_ADDRESS_SYMBOLS          (1),
		.AV_BURSTCOUNT_SYMBOLS       (1),
		.AV_CONSTANT_BURST_BEHAVIOR  (0),
		.UAV_CONSTANT_BURST_BEHAVIOR (0),
		.AV_LINEWRAPBURSTS           (0),
		.AV_REGISTERINCOMINGSIGNALS  (0)
	) sample2lvl_converter_0_ram_translator (
		.clk                    (clk_0_clk_clk),                                                                 //                       clk.clk
		.reset                  (sample2lvl_converter_0_reset_reset_bridge_in_reset_reset),                      //                     reset.reset
		.uav_address            (sample2lvl_converter_0_ram_translator_avalon_universal_master_0_address),       // avalon_universal_master_0.address
		.uav_burstcount         (sample2lvl_converter_0_ram_translator_avalon_universal_master_0_burstcount),    //                          .burstcount
		.uav_read               (sample2lvl_converter_0_ram_translator_avalon_universal_master_0_read),          //                          .read
		.uav_write              (sample2lvl_converter_0_ram_translator_avalon_universal_master_0_write),         //                          .write
		.uav_waitrequest        (sample2lvl_converter_0_ram_translator_avalon_universal_master_0_waitrequest),   //                          .waitrequest
		.uav_readdatavalid      (sample2lvl_converter_0_ram_translator_avalon_universal_master_0_readdatavalid), //                          .readdatavalid
		.uav_byteenable         (sample2lvl_converter_0_ram_translator_avalon_universal_master_0_byteenable),    //                          .byteenable
		.uav_readdata           (sample2lvl_converter_0_ram_translator_avalon_universal_master_0_readdata),      //                          .readdata
		.uav_writedata          (sample2lvl_converter_0_ram_translator_avalon_universal_master_0_writedata),     //                          .writedata
		.uav_lock               (sample2lvl_converter_0_ram_translator_avalon_universal_master_0_lock),          //                          .lock
		.uav_debugaccess        (sample2lvl_converter_0_ram_translator_avalon_universal_master_0_debugaccess),   //                          .debugaccess
		.av_address             (sample2lvl_converter_0_ram_address),                                            //      avalon_anti_master_0.address
		.av_waitrequest         (sample2lvl_converter_0_ram_waitrequest),                                        //                          .waitrequest
		.av_byteenable          (sample2lvl_converter_0_ram_byteenable),                                         //                          .byteenable
		.av_chipselect          (sample2lvl_converter_0_ram_chipselect),                                         //                          .chipselect
		.av_read                (sample2lvl_converter_0_ram_read),                                               //                          .read
		.av_readdata            (sample2lvl_converter_0_ram_readdata),                                           //                          .readdata
		.av_write               (sample2lvl_converter_0_ram_write),                                              //                          .write
		.av_writedata           (sample2lvl_converter_0_ram_writedata),                                          //                          .writedata
		.av_burstcount          (1'b1),                                                                          //               (terminated)
		.av_beginbursttransfer  (1'b0),                                                                          //               (terminated)
		.av_begintransfer       (1'b0),                                                                          //               (terminated)
		.av_readdatavalid       (),                                                                              //               (terminated)
		.av_lock                (1'b0),                                                                          //               (terminated)
		.av_debugaccess         (1'b0),                                                                          //               (terminated)
		.uav_clken              (),                                                                              //               (terminated)
		.av_clken               (1'b1),                                                                          //               (terminated)
		.uav_response           (2'b00),                                                                         //               (terminated)
		.av_response            (),                                                                              //               (terminated)
		.uav_writeresponsevalid (1'b0),                                                                          //               (terminated)
		.av_writeresponsevalid  ()                                                                               //               (terminated)
	);

	altera_merlin_slave_translator #(
		.AV_ADDRESS_W                   (9),
		.AV_DATA_W                      (16),
		.UAV_DATA_W                     (16),
		.AV_BURSTCOUNT_W                (1),
		.AV_BYTEENABLE_W                (2),
		.UAV_BYTEENABLE_W               (2),
		.UAV_ADDRESS_W                  (10),
		.UAV_BURSTCOUNT_W               (2),
		.AV_READLATENCY                 (1),
		.USE_READDATAVALID              (0),
		.USE_WAITREQUEST                (0),
		.USE_UAV_CLKEN                  (0),
		.USE_READRESPONSE               (0),
		.USE_WRITERESPONSE              (0),
		.AV_SYMBOLS_PER_WORD            (2),
		.AV_ADDRESS_SYMBOLS             (0),
		.AV_BURSTCOUNT_SYMBOLS          (0),
		.AV_CONSTANT_BURST_BEHAVIOR     (0),
		.UAV_CONSTANT_BURST_BEHAVIOR    (0),
		.AV_REQUIRE_UNALIGNED_ADDRESSES (0),
		.CHIPSELECT_THROUGH_READLATENCY (0),
		.AV_READ_WAIT_CYCLES            (0),
		.AV_WRITE_WAIT_CYCLES           (0),
		.AV_SETUP_WAIT_CYCLES           (0),
		.AV_DATA_HOLD_CYCLES            (0)
	) sample_buffer_s1_translator (
		.clk                    (clk_0_clk_clk),                                                                 //                      clk.clk
		.reset                  (sample2lvl_converter_0_reset_reset_bridge_in_reset_reset),                      //                    reset.reset
		.uav_address            (sample2lvl_converter_0_ram_translator_avalon_universal_master_0_address),       // avalon_universal_slave_0.address
		.uav_burstcount         (sample2lvl_converter_0_ram_translator_avalon_universal_master_0_burstcount),    //                         .burstcount
		.uav_read               (sample2lvl_converter_0_ram_translator_avalon_universal_master_0_read),          //                         .read
		.uav_write              (sample2lvl_converter_0_ram_translator_avalon_universal_master_0_write),         //                         .write
		.uav_waitrequest        (sample2lvl_converter_0_ram_translator_avalon_universal_master_0_waitrequest),   //                         .waitrequest
		.uav_readdatavalid      (sample2lvl_converter_0_ram_translator_avalon_universal_master_0_readdatavalid), //                         .readdatavalid
		.uav_byteenable         (sample2lvl_converter_0_ram_translator_avalon_universal_master_0_byteenable),    //                         .byteenable
		.uav_readdata           (sample2lvl_converter_0_ram_translator_avalon_universal_master_0_readdata),      //                         .readdata
		.uav_writedata          (sample2lvl_converter_0_ram_translator_avalon_universal_master_0_writedata),     //                         .writedata
		.uav_lock               (sample2lvl_converter_0_ram_translator_avalon_universal_master_0_lock),          //                         .lock
		.uav_debugaccess        (sample2lvl_converter_0_ram_translator_avalon_universal_master_0_debugaccess),   //                         .debugaccess
		.av_address             (sample_buffer_s1_address),                                                      //      avalon_anti_slave_0.address
		.av_write               (sample_buffer_s1_write),                                                        //                         .write
		.av_readdata            (sample_buffer_s1_readdata),                                                     //                         .readdata
		.av_writedata           (sample_buffer_s1_writedata),                                                    //                         .writedata
		.av_byteenable          (sample_buffer_s1_byteenable),                                                   //                         .byteenable
		.av_chipselect          (sample_buffer_s1_chipselect),                                                   //                         .chipselect
		.av_clken               (sample_buffer_s1_clken),                                                        //                         .clken
		.av_read                (),                                                                              //              (terminated)
		.av_begintransfer       (),                                                                              //              (terminated)
		.av_beginbursttransfer  (),                                                                              //              (terminated)
		.av_burstcount          (),                                                                              //              (terminated)
		.av_readdatavalid       (1'b0),                                                                          //              (terminated)
		.av_waitrequest         (1'b0),                                                                          //              (terminated)
		.av_writebyteenable     (),                                                                              //              (terminated)
		.av_lock                (),                                                                              //              (terminated)
		.uav_clken              (1'b0),                                                                          //              (terminated)
		.av_debugaccess         (),                                                                              //              (terminated)
		.av_outputenable        (),                                                                              //              (terminated)
		.uav_response           (),                                                                              //              (terminated)
		.av_response            (2'b00),                                                                         //              (terminated)
		.uav_writeresponsevalid (),                                                                              //              (terminated)
		.av_writeresponsevalid  (1'b0)                                                                           //              (terminated)
	);

endmodule
