#ifndef _ALTERA_HPS_DEF_H_
#define _ALTERA_HPS_DEF_H_

/*
 * This file was automatically generated by the swinfo2header utility.
 * 
 * Created from SOPC Builder system 'soc_system' in
 * file 'soc_system.swinfo'.
 */

/*
 * This file contains macros for module 'hps_0' and devices
 * connected to the following masters:
 *   h2f_axi_master
 *   h2f_lw_axi_master
 * 
 * Do not include this header file and another header file created for a
 * different module or master group at the same time.
 * Doing so may result in duplicate macro names.
 * Instead, use the system header file which has macros with unique names.
 */

/*
 * Macros for device 'onchip_RAM', class 'altera_avalon_onchip_memory2'
 * The macros are prefixed with 'ONCHIP_RAM_'.
 * The prefix is the slave descriptor.
 */
#define ONCHIP_RAM_COMPONENT_TYPE altera_avalon_onchip_memory2
#define ONCHIP_RAM_COMPONENT_NAME onchip_RAM
#define ONCHIP_RAM_BASE 0x0
#define ONCHIP_RAM_SPAN 65536
#define ONCHIP_RAM_END 0xffff
#define ONCHIP_RAM_ALLOW_IN_SYSTEM_MEMORY_CONTENT_EDITOR 0
#define ONCHIP_RAM_ALLOW_MRAM_SIM_CONTENTS_ONLY_FILE 0
#define ONCHIP_RAM_CONTENTS_INFO ""
#define ONCHIP_RAM_DUAL_PORT 0
#define ONCHIP_RAM_GUI_RAM_BLOCK_TYPE AUTO
#define ONCHIP_RAM_INIT_CONTENTS_FILE soc_system_onchip_RAM
#define ONCHIP_RAM_INIT_MEM_CONTENT 1
#define ONCHIP_RAM_INSTANCE_ID NONE
#define ONCHIP_RAM_NON_DEFAULT_INIT_FILE_ENABLED 0
#define ONCHIP_RAM_RAM_BLOCK_TYPE AUTO
#define ONCHIP_RAM_READ_DURING_WRITE_MODE DONT_CARE
#define ONCHIP_RAM_SINGLE_CLOCK_OP 0
#define ONCHIP_RAM_SIZE_MULTIPLE 1
#define ONCHIP_RAM_SIZE_VALUE 65536
#define ONCHIP_RAM_WRITABLE 1
#define ONCHIP_RAM_MEMORY_INFO_DAT_SYM_INSTALL_DIR SIM_DIR
#define ONCHIP_RAM_MEMORY_INFO_GENERATE_DAT_SYM 1
#define ONCHIP_RAM_MEMORY_INFO_GENERATE_HEX 1
#define ONCHIP_RAM_MEMORY_INFO_HAS_BYTE_LANE 0
#define ONCHIP_RAM_MEMORY_INFO_HEX_INSTALL_DIR QPF_DIR
#define ONCHIP_RAM_MEMORY_INFO_MEM_INIT_DATA_WIDTH 32
#define ONCHIP_RAM_MEMORY_INFO_MEM_INIT_FILENAME soc_system_onchip_RAM

/*
 * Macros for device 'sysid_qsys', class 'altera_avalon_sysid_qsys'
 * The macros are prefixed with 'SYSID_QSYS_'.
 * The prefix is the slave descriptor.
 */
#define SYSID_QSYS_COMPONENT_TYPE altera_avalon_sysid_qsys
#define SYSID_QSYS_COMPONENT_NAME sysid_qsys
#define SYSID_QSYS_BASE 0x10000
#define SYSID_QSYS_SPAN 8
#define SYSID_QSYS_END 0x10007
#define SYSID_QSYS_ID 2899645186
#define SYSID_QSYS_TIMESTAMP 1523969102

/*
 * Macros for device 'led_pio', class 'altera_avalon_pio'
 * The macros are prefixed with 'LED_PIO_'.
 * The prefix is the slave descriptor.
 */
#define LED_PIO_COMPONENT_TYPE altera_avalon_pio
#define LED_PIO_COMPONENT_NAME led_pio
#define LED_PIO_BASE 0x10040
#define LED_PIO_SPAN 16
#define LED_PIO_END 0x1004f
#define LED_PIO_BIT_CLEARING_EDGE_REGISTER 0
#define LED_PIO_BIT_MODIFYING_OUTPUT_REGISTER 0
#define LED_PIO_CAPTURE 0
#define LED_PIO_DATA_WIDTH 10
#define LED_PIO_DO_TEST_BENCH_WIRING 0
#define LED_PIO_DRIVEN_SIM_VALUE 0
#define LED_PIO_EDGE_TYPE NONE
#define LED_PIO_FREQ 100000000
#define LED_PIO_HAS_IN 0
#define LED_PIO_HAS_OUT 1
#define LED_PIO_HAS_TRI 0
#define LED_PIO_IRQ_TYPE NONE
#define LED_PIO_RESET_VALUE 0

/*
 * Macros for device 'dipsw_pio', class 'altera_avalon_pio'
 * The macros are prefixed with 'DIPSW_PIO_'.
 * The prefix is the slave descriptor.
 */
#define DIPSW_PIO_COMPONENT_TYPE altera_avalon_pio
#define DIPSW_PIO_COMPONENT_NAME dipsw_pio
#define DIPSW_PIO_BASE 0x10080
#define DIPSW_PIO_SPAN 16
#define DIPSW_PIO_END 0x1008f
#define DIPSW_PIO_BIT_CLEARING_EDGE_REGISTER 0
#define DIPSW_PIO_BIT_MODIFYING_OUTPUT_REGISTER 0
#define DIPSW_PIO_CAPTURE 0
#define DIPSW_PIO_DATA_WIDTH 10
#define DIPSW_PIO_DO_TEST_BENCH_WIRING 1
#define DIPSW_PIO_DRIVEN_SIM_VALUE 0
#define DIPSW_PIO_EDGE_TYPE NONE
#define DIPSW_PIO_FREQ 100000000
#define DIPSW_PIO_HAS_IN 1
#define DIPSW_PIO_HAS_OUT 0
#define DIPSW_PIO_HAS_TRI 0
#define DIPSW_PIO_IRQ_TYPE NONE
#define DIPSW_PIO_RESET_VALUE 0

/*
 * Macros for device 'button_pio', class 'altera_avalon_pio'
 * The macros are prefixed with 'BUTTON_PIO_'.
 * The prefix is the slave descriptor.
 */
#define BUTTON_PIO_COMPONENT_TYPE altera_avalon_pio
#define BUTTON_PIO_COMPONENT_NAME button_pio
#define BUTTON_PIO_BASE 0x100c0
#define BUTTON_PIO_SPAN 16
#define BUTTON_PIO_END 0x100cf
#define BUTTON_PIO_BIT_CLEARING_EDGE_REGISTER 0
#define BUTTON_PIO_BIT_MODIFYING_OUTPUT_REGISTER 0
#define BUTTON_PIO_CAPTURE 0
#define BUTTON_PIO_DATA_WIDTH 4
#define BUTTON_PIO_DO_TEST_BENCH_WIRING 1
#define BUTTON_PIO_DRIVEN_SIM_VALUE 0
#define BUTTON_PIO_EDGE_TYPE NONE
#define BUTTON_PIO_FREQ 100000000
#define BUTTON_PIO_HAS_IN 1
#define BUTTON_PIO_HAS_OUT 0
#define BUTTON_PIO_HAS_TRI 0
#define BUTTON_PIO_IRQ_TYPE NONE
#define BUTTON_PIO_RESET_VALUE 0

/*
 * Macros for device 'sgdma_mm2st', class 'altera_avalon_sgdma'
 * The macros are prefixed with 'SGDMA_MM2ST_'.
 * The prefix is the slave descriptor.
 */
#define SGDMA_MM2ST_COMPONENT_TYPE altera_avalon_sgdma
#define SGDMA_MM2ST_COMPONENT_NAME sgdma_mm2st
#define SGDMA_MM2ST_BASE 0x20000
#define SGDMA_MM2ST_SPAN 64
#define SGDMA_MM2ST_END 0x2003f
#define SGDMA_MM2ST_ADDRESS_WIDTH 32
#define SGDMA_MM2ST_ALWAYS_DO_MAX_BURST 1
#define SGDMA_MM2ST_ATLANTIC_CHANNEL_DATA_WIDTH 4
#define SGDMA_MM2ST_AVALON_MM_BYTE_REORDER_MODE 0
#define SGDMA_MM2ST_BURST_DATA_WIDTH 8
#define SGDMA_MM2ST_BURST_TRANSFER 0
#define SGDMA_MM2ST_BYTES_TO_TRANSFER_DATA_WIDTH 16
#define SGDMA_MM2ST_CHAIN_WRITEBACK_DATA_WIDTH 32
#define SGDMA_MM2ST_COMMAND_FIFO_DATA_WIDTH 104
#define SGDMA_MM2ST_CONTROL_DATA_WIDTH 8
#define SGDMA_MM2ST_CONTROL_SLAVE_ADDRESS_WIDTH 4
#define SGDMA_MM2ST_CONTROL_SLAVE_DATA_WIDTH 32
#define SGDMA_MM2ST_DESCRIPTOR_READ_BURST 0
#define SGDMA_MM2ST_DESC_DATA_WIDTH 32
#define SGDMA_MM2ST_HAS_READ_BLOCK 1
#define SGDMA_MM2ST_HAS_WRITE_BLOCK 0
#define SGDMA_MM2ST_IN_ERROR_WIDTH 0
#define SGDMA_MM2ST_OUT_ERROR_WIDTH 0
#define SGDMA_MM2ST_READ_BLOCK_DATA_WIDTH 16
#define SGDMA_MM2ST_READ_BURSTCOUNT_WIDTH 4
#define SGDMA_MM2ST_STATUS_TOKEN_DATA_WIDTH 24
#define SGDMA_MM2ST_STREAM_DATA_WIDTH 16
#define SGDMA_MM2ST_SYMBOLS_PER_BEAT 2
#define SGDMA_MM2ST_UNALIGNED_TRANSFER 0
#define SGDMA_MM2ST_WRITE_BLOCK_DATA_WIDTH 16
#define SGDMA_MM2ST_WRITE_BURSTCOUNT_WIDTH 4

/*
 * Macros for device 'hps_0_axi_sdram', class 'axi_sdram'
 * Path to the device is from the master group 'sgdma_mm2st_m_read'.
 * The macros are prefixed with 'SGDMA_MM2ST_M_READ_HPS_0_AXI_SDRAM_'.
 * The prefix is the master group descriptor and the slave descriptor.
 */
#define SGDMA_MM2ST_M_READ_HPS_0_AXI_SDRAM_COMPONENT_TYPE axi_sdram
#define SGDMA_MM2ST_M_READ_HPS_0_AXI_SDRAM_COMPONENT_NAME hps_0_axi_sdram
#define SGDMA_MM2ST_M_READ_HPS_0_AXI_SDRAM_BASE 0x0
#define SGDMA_MM2ST_M_READ_HPS_0_AXI_SDRAM_SPAN 0x80000000
#define SGDMA_MM2ST_M_READ_HPS_0_AXI_SDRAM_END 0x7fffffff
#define SGDMA_MM2ST_M_READ_HPS_0_AXI_SDRAM_SIZE_MULTIPLE 1
#define SGDMA_MM2ST_M_READ_HPS_0_AXI_SDRAM_SIZE_VALUE 1<<31
#define SGDMA_MM2ST_M_READ_HPS_0_AXI_SDRAM_WRITABLE 1
#define SGDMA_MM2ST_M_READ_HPS_0_AXI_SDRAM_MEMORY_INFO_GENERATE_DAT_SYM 0
#define SGDMA_MM2ST_M_READ_HPS_0_AXI_SDRAM_MEMORY_INFO_GENERATE_HEX 0
#define SGDMA_MM2ST_M_READ_HPS_0_AXI_SDRAM_MEMORY_INFO_MEM_INIT_DATA_WIDTH 31

/*
 * Macros for device 'hps_0_gmac0', class 'stmmac'
 * Path to the device is from the master group 'sgdma_mm2st_m_read'.
 * The macros are prefixed with 'SGDMA_MM2ST_M_READ_HPS_0_GMAC0_'.
 * The prefix is the master group descriptor and the slave descriptor.
 */
#define SGDMA_MM2ST_M_READ_HPS_0_GMAC0_COMPONENT_TYPE stmmac
#define SGDMA_MM2ST_M_READ_HPS_0_GMAC0_COMPONENT_NAME hps_0_gmac0
#define SGDMA_MM2ST_M_READ_HPS_0_GMAC0_BASE 0xff700000
#define SGDMA_MM2ST_M_READ_HPS_0_GMAC0_SPAN 8192
#define SGDMA_MM2ST_M_READ_HPS_0_GMAC0_END 0xff701fff

/*
 * Macros for device 'hps_0_gmac1', class 'stmmac'
 * Path to the device is from the master group 'sgdma_mm2st_m_read'.
 * The macros are prefixed with 'SGDMA_MM2ST_M_READ_HPS_0_GMAC1_'.
 * The prefix is the master group descriptor and the slave descriptor.
 */
#define SGDMA_MM2ST_M_READ_HPS_0_GMAC1_COMPONENT_TYPE stmmac
#define SGDMA_MM2ST_M_READ_HPS_0_GMAC1_COMPONENT_NAME hps_0_gmac1
#define SGDMA_MM2ST_M_READ_HPS_0_GMAC1_BASE 0xff702000
#define SGDMA_MM2ST_M_READ_HPS_0_GMAC1_SPAN 8192
#define SGDMA_MM2ST_M_READ_HPS_0_GMAC1_END 0xff703fff

/*
 * Macros for device 'hps_0_sdmmc', class 'sdmmc'
 * Path to the device is from the master group 'sgdma_mm2st_m_read'.
 * The macros are prefixed with 'SGDMA_MM2ST_M_READ_HPS_0_SDMMC_'.
 * The prefix is the master group descriptor and the slave descriptor.
 */
#define SGDMA_MM2ST_M_READ_HPS_0_SDMMC_COMPONENT_TYPE sdmmc
#define SGDMA_MM2ST_M_READ_HPS_0_SDMMC_COMPONENT_NAME hps_0_sdmmc
#define SGDMA_MM2ST_M_READ_HPS_0_SDMMC_BASE 0xff704000
#define SGDMA_MM2ST_M_READ_HPS_0_SDMMC_SPAN 4096
#define SGDMA_MM2ST_M_READ_HPS_0_SDMMC_END 0xff704fff

/*
 * Macros for device 'hps_0_qspi', class 'cadence_qspi'
 * Path to the device is from the master group 'sgdma_mm2st_m_read'.
 * The macros are prefixed with 'SGDMA_MM2ST_M_READ_HPS_0_QSPI_'.
 * The prefix is the master group descriptor and the slave descriptor.
 */
#define SGDMA_MM2ST_M_READ_HPS_0_QSPI_COMPONENT_TYPE cadence_qspi
#define SGDMA_MM2ST_M_READ_HPS_0_QSPI_COMPONENT_NAME hps_0_qspi
#define SGDMA_MM2ST_M_READ_HPS_0_QSPI_BASE 0xff705000
#define SGDMA_MM2ST_M_READ_HPS_0_QSPI_SPAN 256
#define SGDMA_MM2ST_M_READ_HPS_0_QSPI_END 0xff7050ff

/*
 * Macros for device 'hps_0_fpgamgr', class 'altera_fpgamgr'
 * Path to the device is from the master group 'sgdma_mm2st_m_read'.
 * The macros are prefixed with 'SGDMA_MM2ST_M_READ_HPS_0_FPGAMGR_'.
 * The prefix is the master group descriptor and the slave descriptor.
 */
#define SGDMA_MM2ST_M_READ_HPS_0_FPGAMGR_COMPONENT_TYPE altera_fpgamgr
#define SGDMA_MM2ST_M_READ_HPS_0_FPGAMGR_COMPONENT_NAME hps_0_fpgamgr
#define SGDMA_MM2ST_M_READ_HPS_0_FPGAMGR_BASE 0xff706000
#define SGDMA_MM2ST_M_READ_HPS_0_FPGAMGR_SPAN 4096
#define SGDMA_MM2ST_M_READ_HPS_0_FPGAMGR_END 0xff706fff

/*
 * Macros for device 'hps_0_gpio0', class 'dw_gpio'
 * Path to the device is from the master group 'sgdma_mm2st_m_read'.
 * The macros are prefixed with 'SGDMA_MM2ST_M_READ_HPS_0_GPIO0_'.
 * The prefix is the master group descriptor and the slave descriptor.
 */
#define SGDMA_MM2ST_M_READ_HPS_0_GPIO0_COMPONENT_TYPE dw_gpio
#define SGDMA_MM2ST_M_READ_HPS_0_GPIO0_COMPONENT_NAME hps_0_gpio0
#define SGDMA_MM2ST_M_READ_HPS_0_GPIO0_BASE 0xff708000
#define SGDMA_MM2ST_M_READ_HPS_0_GPIO0_SPAN 256
#define SGDMA_MM2ST_M_READ_HPS_0_GPIO0_END 0xff7080ff

/*
 * Macros for device 'hps_0_gpio1', class 'dw_gpio'
 * Path to the device is from the master group 'sgdma_mm2st_m_read'.
 * The macros are prefixed with 'SGDMA_MM2ST_M_READ_HPS_0_GPIO1_'.
 * The prefix is the master group descriptor and the slave descriptor.
 */
#define SGDMA_MM2ST_M_READ_HPS_0_GPIO1_COMPONENT_TYPE dw_gpio
#define SGDMA_MM2ST_M_READ_HPS_0_GPIO1_COMPONENT_NAME hps_0_gpio1
#define SGDMA_MM2ST_M_READ_HPS_0_GPIO1_BASE 0xff709000
#define SGDMA_MM2ST_M_READ_HPS_0_GPIO1_SPAN 256
#define SGDMA_MM2ST_M_READ_HPS_0_GPIO1_END 0xff7090ff

/*
 * Macros for device 'hps_0_gpio2', class 'dw_gpio'
 * Path to the device is from the master group 'sgdma_mm2st_m_read'.
 * The macros are prefixed with 'SGDMA_MM2ST_M_READ_HPS_0_GPIO2_'.
 * The prefix is the master group descriptor and the slave descriptor.
 */
#define SGDMA_MM2ST_M_READ_HPS_0_GPIO2_COMPONENT_TYPE dw_gpio
#define SGDMA_MM2ST_M_READ_HPS_0_GPIO2_COMPONENT_NAME hps_0_gpio2
#define SGDMA_MM2ST_M_READ_HPS_0_GPIO2_BASE 0xff70a000
#define SGDMA_MM2ST_M_READ_HPS_0_GPIO2_SPAN 256
#define SGDMA_MM2ST_M_READ_HPS_0_GPIO2_END 0xff70a0ff

/*
 * Macros for device 'hps_0_l3regs', class 'altera_l3regs'
 * Path to the device is from the master group 'sgdma_mm2st_m_read'.
 * The macros are prefixed with 'SGDMA_MM2ST_M_READ_HPS_0_L3REGS_'.
 * The prefix is the master group descriptor and the slave descriptor.
 */
#define SGDMA_MM2ST_M_READ_HPS_0_L3REGS_COMPONENT_TYPE altera_l3regs
#define SGDMA_MM2ST_M_READ_HPS_0_L3REGS_COMPONENT_NAME hps_0_l3regs
#define SGDMA_MM2ST_M_READ_HPS_0_L3REGS_BASE 0xff800000
#define SGDMA_MM2ST_M_READ_HPS_0_L3REGS_SPAN 4096
#define SGDMA_MM2ST_M_READ_HPS_0_L3REGS_END 0xff800fff

/*
 * Macros for device 'hps_0_nand0', class 'denali_nand'
 * Path to the device is from the master group 'sgdma_mm2st_m_read'.
 * The macros are prefixed with 'SGDMA_MM2ST_M_READ_HPS_0_NAND0_'.
 * The prefix is the master group descriptor and the slave descriptor.
 */
#define SGDMA_MM2ST_M_READ_HPS_0_NAND0_COMPONENT_TYPE denali_nand
#define SGDMA_MM2ST_M_READ_HPS_0_NAND0_COMPONENT_NAME hps_0_nand0
#define SGDMA_MM2ST_M_READ_HPS_0_NAND0_BASE 0xff900000
#define SGDMA_MM2ST_M_READ_HPS_0_NAND0_SPAN 65536
#define SGDMA_MM2ST_M_READ_HPS_0_NAND0_END 0xff90ffff

/*
 * Macros for device 'hps_0_usb0', class 'usb'
 * Path to the device is from the master group 'sgdma_mm2st_m_read'.
 * The macros are prefixed with 'SGDMA_MM2ST_M_READ_HPS_0_USB0_'.
 * The prefix is the master group descriptor and the slave descriptor.
 */
#define SGDMA_MM2ST_M_READ_HPS_0_USB0_COMPONENT_TYPE usb
#define SGDMA_MM2ST_M_READ_HPS_0_USB0_COMPONENT_NAME hps_0_usb0
#define SGDMA_MM2ST_M_READ_HPS_0_USB0_BASE 0xffb00000
#define SGDMA_MM2ST_M_READ_HPS_0_USB0_SPAN 262144
#define SGDMA_MM2ST_M_READ_HPS_0_USB0_END 0xffb3ffff

/*
 * Macros for device 'hps_0_usb1', class 'usb'
 * Path to the device is from the master group 'sgdma_mm2st_m_read'.
 * The macros are prefixed with 'SGDMA_MM2ST_M_READ_HPS_0_USB1_'.
 * The prefix is the master group descriptor and the slave descriptor.
 */
#define SGDMA_MM2ST_M_READ_HPS_0_USB1_COMPONENT_TYPE usb
#define SGDMA_MM2ST_M_READ_HPS_0_USB1_COMPONENT_NAME hps_0_usb1
#define SGDMA_MM2ST_M_READ_HPS_0_USB1_BASE 0xffb40000
#define SGDMA_MM2ST_M_READ_HPS_0_USB1_SPAN 262144
#define SGDMA_MM2ST_M_READ_HPS_0_USB1_END 0xffb7ffff

/*
 * Macros for device 'hps_0_dcan0', class 'bosch_dcan'
 * Path to the device is from the master group 'sgdma_mm2st_m_read'.
 * The macros are prefixed with 'SGDMA_MM2ST_M_READ_HPS_0_DCAN0_'.
 * The prefix is the master group descriptor and the slave descriptor.
 */
#define SGDMA_MM2ST_M_READ_HPS_0_DCAN0_COMPONENT_TYPE bosch_dcan
#define SGDMA_MM2ST_M_READ_HPS_0_DCAN0_COMPONENT_NAME hps_0_dcan0
#define SGDMA_MM2ST_M_READ_HPS_0_DCAN0_BASE 0xffc00000
#define SGDMA_MM2ST_M_READ_HPS_0_DCAN0_SPAN 4096
#define SGDMA_MM2ST_M_READ_HPS_0_DCAN0_END 0xffc00fff

/*
 * Macros for device 'hps_0_dcan1', class 'bosch_dcan'
 * Path to the device is from the master group 'sgdma_mm2st_m_read'.
 * The macros are prefixed with 'SGDMA_MM2ST_M_READ_HPS_0_DCAN1_'.
 * The prefix is the master group descriptor and the slave descriptor.
 */
#define SGDMA_MM2ST_M_READ_HPS_0_DCAN1_COMPONENT_TYPE bosch_dcan
#define SGDMA_MM2ST_M_READ_HPS_0_DCAN1_COMPONENT_NAME hps_0_dcan1
#define SGDMA_MM2ST_M_READ_HPS_0_DCAN1_BASE 0xffc01000
#define SGDMA_MM2ST_M_READ_HPS_0_DCAN1_SPAN 4096
#define SGDMA_MM2ST_M_READ_HPS_0_DCAN1_END 0xffc01fff

/*
 * Macros for device 'hps_0_uart0', class 'snps_uart'
 * Path to the device is from the master group 'sgdma_mm2st_m_read'.
 * The macros are prefixed with 'SGDMA_MM2ST_M_READ_HPS_0_UART0_'.
 * The prefix is the master group descriptor and the slave descriptor.
 */
#define SGDMA_MM2ST_M_READ_HPS_0_UART0_COMPONENT_TYPE snps_uart
#define SGDMA_MM2ST_M_READ_HPS_0_UART0_COMPONENT_NAME hps_0_uart0
#define SGDMA_MM2ST_M_READ_HPS_0_UART0_BASE 0xffc02000
#define SGDMA_MM2ST_M_READ_HPS_0_UART0_SPAN 256
#define SGDMA_MM2ST_M_READ_HPS_0_UART0_END 0xffc020ff
#define SGDMA_MM2ST_M_READ_HPS_0_UART0_FIFO_DEPTH 128
#define SGDMA_MM2ST_M_READ_HPS_0_UART0_FIFO_HWFC 0
#define SGDMA_MM2ST_M_READ_HPS_0_UART0_FIFO_MODE 1
#define SGDMA_MM2ST_M_READ_HPS_0_UART0_FIFO_SWFC 0
#define SGDMA_MM2ST_M_READ_HPS_0_UART0_FREQ 100000000

/*
 * Macros for device 'hps_0_uart1', class 'snps_uart'
 * Path to the device is from the master group 'sgdma_mm2st_m_read'.
 * The macros are prefixed with 'SGDMA_MM2ST_M_READ_HPS_0_UART1_'.
 * The prefix is the master group descriptor and the slave descriptor.
 */
#define SGDMA_MM2ST_M_READ_HPS_0_UART1_COMPONENT_TYPE snps_uart
#define SGDMA_MM2ST_M_READ_HPS_0_UART1_COMPONENT_NAME hps_0_uart1
#define SGDMA_MM2ST_M_READ_HPS_0_UART1_BASE 0xffc03000
#define SGDMA_MM2ST_M_READ_HPS_0_UART1_SPAN 256
#define SGDMA_MM2ST_M_READ_HPS_0_UART1_END 0xffc030ff
#define SGDMA_MM2ST_M_READ_HPS_0_UART1_FIFO_DEPTH 128
#define SGDMA_MM2ST_M_READ_HPS_0_UART1_FIFO_HWFC 0
#define SGDMA_MM2ST_M_READ_HPS_0_UART1_FIFO_MODE 1
#define SGDMA_MM2ST_M_READ_HPS_0_UART1_FIFO_SWFC 0
#define SGDMA_MM2ST_M_READ_HPS_0_UART1_FREQ 100000000

/*
 * Macros for device 'hps_0_i2c0', class 'designware_i2c'
 * Path to the device is from the master group 'sgdma_mm2st_m_read'.
 * The macros are prefixed with 'SGDMA_MM2ST_M_READ_HPS_0_I2C0_'.
 * The prefix is the master group descriptor and the slave descriptor.
 */
#define SGDMA_MM2ST_M_READ_HPS_0_I2C0_COMPONENT_TYPE designware_i2c
#define SGDMA_MM2ST_M_READ_HPS_0_I2C0_COMPONENT_NAME hps_0_i2c0
#define SGDMA_MM2ST_M_READ_HPS_0_I2C0_BASE 0xffc04000
#define SGDMA_MM2ST_M_READ_HPS_0_I2C0_SPAN 256
#define SGDMA_MM2ST_M_READ_HPS_0_I2C0_END 0xffc040ff

/*
 * Macros for device 'hps_0_i2c1', class 'designware_i2c'
 * Path to the device is from the master group 'sgdma_mm2st_m_read'.
 * The macros are prefixed with 'SGDMA_MM2ST_M_READ_HPS_0_I2C1_'.
 * The prefix is the master group descriptor and the slave descriptor.
 */
#define SGDMA_MM2ST_M_READ_HPS_0_I2C1_COMPONENT_TYPE designware_i2c
#define SGDMA_MM2ST_M_READ_HPS_0_I2C1_COMPONENT_NAME hps_0_i2c1
#define SGDMA_MM2ST_M_READ_HPS_0_I2C1_BASE 0xffc05000
#define SGDMA_MM2ST_M_READ_HPS_0_I2C1_SPAN 256
#define SGDMA_MM2ST_M_READ_HPS_0_I2C1_END 0xffc050ff

/*
 * Macros for device 'hps_0_i2c2', class 'designware_i2c'
 * Path to the device is from the master group 'sgdma_mm2st_m_read'.
 * The macros are prefixed with 'SGDMA_MM2ST_M_READ_HPS_0_I2C2_'.
 * The prefix is the master group descriptor and the slave descriptor.
 */
#define SGDMA_MM2ST_M_READ_HPS_0_I2C2_COMPONENT_TYPE designware_i2c
#define SGDMA_MM2ST_M_READ_HPS_0_I2C2_COMPONENT_NAME hps_0_i2c2
#define SGDMA_MM2ST_M_READ_HPS_0_I2C2_BASE 0xffc06000
#define SGDMA_MM2ST_M_READ_HPS_0_I2C2_SPAN 256
#define SGDMA_MM2ST_M_READ_HPS_0_I2C2_END 0xffc060ff

/*
 * Macros for device 'hps_0_i2c3', class 'designware_i2c'
 * Path to the device is from the master group 'sgdma_mm2st_m_read'.
 * The macros are prefixed with 'SGDMA_MM2ST_M_READ_HPS_0_I2C3_'.
 * The prefix is the master group descriptor and the slave descriptor.
 */
#define SGDMA_MM2ST_M_READ_HPS_0_I2C3_COMPONENT_TYPE designware_i2c
#define SGDMA_MM2ST_M_READ_HPS_0_I2C3_COMPONENT_NAME hps_0_i2c3
#define SGDMA_MM2ST_M_READ_HPS_0_I2C3_BASE 0xffc07000
#define SGDMA_MM2ST_M_READ_HPS_0_I2C3_SPAN 256
#define SGDMA_MM2ST_M_READ_HPS_0_I2C3_END 0xffc070ff

/*
 * Macros for device 'hps_0_timer0', class 'dw_apb_timer_sp'
 * Path to the device is from the master group 'sgdma_mm2st_m_read'.
 * The macros are prefixed with 'SGDMA_MM2ST_M_READ_HPS_0_TIMER0_'.
 * The prefix is the master group descriptor and the slave descriptor.
 */
#define SGDMA_MM2ST_M_READ_HPS_0_TIMER0_COMPONENT_TYPE dw_apb_timer_sp
#define SGDMA_MM2ST_M_READ_HPS_0_TIMER0_COMPONENT_NAME hps_0_timer0
#define SGDMA_MM2ST_M_READ_HPS_0_TIMER0_BASE 0xffc08000
#define SGDMA_MM2ST_M_READ_HPS_0_TIMER0_SPAN 256
#define SGDMA_MM2ST_M_READ_HPS_0_TIMER0_END 0xffc080ff

/*
 * Macros for device 'hps_0_timer1', class 'dw_apb_timer_sp'
 * Path to the device is from the master group 'sgdma_mm2st_m_read'.
 * The macros are prefixed with 'SGDMA_MM2ST_M_READ_HPS_0_TIMER1_'.
 * The prefix is the master group descriptor and the slave descriptor.
 */
#define SGDMA_MM2ST_M_READ_HPS_0_TIMER1_COMPONENT_TYPE dw_apb_timer_sp
#define SGDMA_MM2ST_M_READ_HPS_0_TIMER1_COMPONENT_NAME hps_0_timer1
#define SGDMA_MM2ST_M_READ_HPS_0_TIMER1_BASE 0xffc09000
#define SGDMA_MM2ST_M_READ_HPS_0_TIMER1_SPAN 256
#define SGDMA_MM2ST_M_READ_HPS_0_TIMER1_END 0xffc090ff

/*
 * Macros for device 'hps_0_sdrctl', class 'altera_sdrctl'
 * Path to the device is from the master group 'sgdma_mm2st_m_read'.
 * The macros are prefixed with 'SGDMA_MM2ST_M_READ_HPS_0_SDRCTL_'.
 * The prefix is the master group descriptor and the slave descriptor.
 */
#define SGDMA_MM2ST_M_READ_HPS_0_SDRCTL_COMPONENT_TYPE altera_sdrctl
#define SGDMA_MM2ST_M_READ_HPS_0_SDRCTL_COMPONENT_NAME hps_0_sdrctl
#define SGDMA_MM2ST_M_READ_HPS_0_SDRCTL_BASE 0xffc25000
#define SGDMA_MM2ST_M_READ_HPS_0_SDRCTL_SPAN 4096
#define SGDMA_MM2ST_M_READ_HPS_0_SDRCTL_END 0xffc25fff

/*
 * Macros for device 'hps_0_timer2', class 'dw_apb_timer_osc'
 * Path to the device is from the master group 'sgdma_mm2st_m_read'.
 * The macros are prefixed with 'SGDMA_MM2ST_M_READ_HPS_0_TIMER2_'.
 * The prefix is the master group descriptor and the slave descriptor.
 */
#define SGDMA_MM2ST_M_READ_HPS_0_TIMER2_COMPONENT_TYPE dw_apb_timer_osc
#define SGDMA_MM2ST_M_READ_HPS_0_TIMER2_COMPONENT_NAME hps_0_timer2
#define SGDMA_MM2ST_M_READ_HPS_0_TIMER2_BASE 0xffd00000
#define SGDMA_MM2ST_M_READ_HPS_0_TIMER2_SPAN 256
#define SGDMA_MM2ST_M_READ_HPS_0_TIMER2_END 0xffd000ff

/*
 * Macros for device 'hps_0_timer3', class 'dw_apb_timer_osc'
 * Path to the device is from the master group 'sgdma_mm2st_m_read'.
 * The macros are prefixed with 'SGDMA_MM2ST_M_READ_HPS_0_TIMER3_'.
 * The prefix is the master group descriptor and the slave descriptor.
 */
#define SGDMA_MM2ST_M_READ_HPS_0_TIMER3_COMPONENT_TYPE dw_apb_timer_osc
#define SGDMA_MM2ST_M_READ_HPS_0_TIMER3_COMPONENT_NAME hps_0_timer3
#define SGDMA_MM2ST_M_READ_HPS_0_TIMER3_BASE 0xffd01000
#define SGDMA_MM2ST_M_READ_HPS_0_TIMER3_SPAN 256
#define SGDMA_MM2ST_M_READ_HPS_0_TIMER3_END 0xffd010ff

/*
 * Macros for device 'hps_0_clkmgr', class 'asimov_clkmgr'
 * Path to the device is from the master group 'sgdma_mm2st_m_read'.
 * The macros are prefixed with 'SGDMA_MM2ST_M_READ_HPS_0_CLKMGR_'.
 * The prefix is the master group descriptor and the slave descriptor.
 */
#define SGDMA_MM2ST_M_READ_HPS_0_CLKMGR_COMPONENT_TYPE asimov_clkmgr
#define SGDMA_MM2ST_M_READ_HPS_0_CLKMGR_COMPONENT_NAME hps_0_clkmgr
#define SGDMA_MM2ST_M_READ_HPS_0_CLKMGR_BASE 0xffd04000
#define SGDMA_MM2ST_M_READ_HPS_0_CLKMGR_SPAN 4096
#define SGDMA_MM2ST_M_READ_HPS_0_CLKMGR_END 0xffd04fff

/*
 * Macros for device 'hps_0_rstmgr', class 'altera_rstmgr'
 * Path to the device is from the master group 'sgdma_mm2st_m_read'.
 * The macros are prefixed with 'SGDMA_MM2ST_M_READ_HPS_0_RSTMGR_'.
 * The prefix is the master group descriptor and the slave descriptor.
 */
#define SGDMA_MM2ST_M_READ_HPS_0_RSTMGR_COMPONENT_TYPE altera_rstmgr
#define SGDMA_MM2ST_M_READ_HPS_0_RSTMGR_COMPONENT_NAME hps_0_rstmgr
#define SGDMA_MM2ST_M_READ_HPS_0_RSTMGR_BASE 0xffd05000
#define SGDMA_MM2ST_M_READ_HPS_0_RSTMGR_SPAN 256
#define SGDMA_MM2ST_M_READ_HPS_0_RSTMGR_END 0xffd050ff

/*
 * Macros for device 'hps_0_sysmgr', class 'altera_sysmgr'
 * Path to the device is from the master group 'sgdma_mm2st_m_read'.
 * The macros are prefixed with 'SGDMA_MM2ST_M_READ_HPS_0_SYSMGR_'.
 * The prefix is the master group descriptor and the slave descriptor.
 */
#define SGDMA_MM2ST_M_READ_HPS_0_SYSMGR_COMPONENT_TYPE altera_sysmgr
#define SGDMA_MM2ST_M_READ_HPS_0_SYSMGR_COMPONENT_NAME hps_0_sysmgr
#define SGDMA_MM2ST_M_READ_HPS_0_SYSMGR_BASE 0xffd08000
#define SGDMA_MM2ST_M_READ_HPS_0_SYSMGR_SPAN 1024
#define SGDMA_MM2ST_M_READ_HPS_0_SYSMGR_END 0xffd083ff

/*
 * Macros for device 'hps_0_dma', class 'arm_pl330_dma'
 * Path to the device is from the master group 'sgdma_mm2st_m_read'.
 * The macros are prefixed with 'SGDMA_MM2ST_M_READ_HPS_0_DMA_'.
 * The prefix is the master group descriptor and the slave descriptor.
 */
#define SGDMA_MM2ST_M_READ_HPS_0_DMA_COMPONENT_TYPE arm_pl330_dma
#define SGDMA_MM2ST_M_READ_HPS_0_DMA_COMPONENT_NAME hps_0_dma
#define SGDMA_MM2ST_M_READ_HPS_0_DMA_BASE 0xffe01000
#define SGDMA_MM2ST_M_READ_HPS_0_DMA_SPAN 4096
#define SGDMA_MM2ST_M_READ_HPS_0_DMA_END 0xffe01fff

/*
 * Macros for device 'hps_0_spim0', class 'spi'
 * Path to the device is from the master group 'sgdma_mm2st_m_read'.
 * The macros are prefixed with 'SGDMA_MM2ST_M_READ_HPS_0_SPIM0_'.
 * The prefix is the master group descriptor and the slave descriptor.
 */
#define SGDMA_MM2ST_M_READ_HPS_0_SPIM0_COMPONENT_TYPE spi
#define SGDMA_MM2ST_M_READ_HPS_0_SPIM0_COMPONENT_NAME hps_0_spim0
#define SGDMA_MM2ST_M_READ_HPS_0_SPIM0_BASE 0xfff00000
#define SGDMA_MM2ST_M_READ_HPS_0_SPIM0_SPAN 256
#define SGDMA_MM2ST_M_READ_HPS_0_SPIM0_END 0xfff000ff

/*
 * Macros for device 'hps_0_spim1', class 'spi'
 * Path to the device is from the master group 'sgdma_mm2st_m_read'.
 * The macros are prefixed with 'SGDMA_MM2ST_M_READ_HPS_0_SPIM1_'.
 * The prefix is the master group descriptor and the slave descriptor.
 */
#define SGDMA_MM2ST_M_READ_HPS_0_SPIM1_COMPONENT_TYPE spi
#define SGDMA_MM2ST_M_READ_HPS_0_SPIM1_COMPONENT_NAME hps_0_spim1
#define SGDMA_MM2ST_M_READ_HPS_0_SPIM1_BASE 0xfff01000
#define SGDMA_MM2ST_M_READ_HPS_0_SPIM1_SPAN 256
#define SGDMA_MM2ST_M_READ_HPS_0_SPIM1_END 0xfff010ff

/*
 * Macros for device 'hps_0_timer', class 'arm_internal_timer'
 * Path to the device is from the master group 'sgdma_mm2st_m_read'.
 * The macros are prefixed with 'SGDMA_MM2ST_M_READ_HPS_0_TIMER_'.
 * The prefix is the master group descriptor and the slave descriptor.
 */
#define SGDMA_MM2ST_M_READ_HPS_0_TIMER_COMPONENT_TYPE arm_internal_timer
#define SGDMA_MM2ST_M_READ_HPS_0_TIMER_COMPONENT_NAME hps_0_timer
#define SGDMA_MM2ST_M_READ_HPS_0_TIMER_BASE 0xfffec600
#define SGDMA_MM2ST_M_READ_HPS_0_TIMER_SPAN 256
#define SGDMA_MM2ST_M_READ_HPS_0_TIMER_END 0xfffec6ff

/*
 * Macros for device 'hps_0_arm_gic_0', class 'arm_gic'
 * Path to the device is from the master group 'sgdma_mm2st_m_read'.
 * The macros are prefixed with 'SGDMA_MM2ST_M_READ_HPS_0_ARM_GIC_0_'.
 * The prefix is the master group descriptor and the slave descriptor.
 */
#define SGDMA_MM2ST_M_READ_HPS_0_ARM_GIC_0_COMPONENT_TYPE arm_gic
#define SGDMA_MM2ST_M_READ_HPS_0_ARM_GIC_0_COMPONENT_NAME hps_0_arm_gic_0
#define SGDMA_MM2ST_M_READ_HPS_0_ARM_GIC_0_BASE 0xfffed000
#define SGDMA_MM2ST_M_READ_HPS_0_ARM_GIC_0_SPAN 4096
#define SGDMA_MM2ST_M_READ_HPS_0_ARM_GIC_0_END 0xfffedfff

/*
 * Macros for device 'hps_0_L2', class 'arm_pl310_L2'
 * Path to the device is from the master group 'sgdma_mm2st_m_read'.
 * The macros are prefixed with 'SGDMA_MM2ST_M_READ_HPS_0_L2_'.
 * The prefix is the master group descriptor and the slave descriptor.
 */
#define SGDMA_MM2ST_M_READ_HPS_0_L2_COMPONENT_TYPE arm_pl310_L2
#define SGDMA_MM2ST_M_READ_HPS_0_L2_COMPONENT_NAME hps_0_L2
#define SGDMA_MM2ST_M_READ_HPS_0_L2_BASE 0xfffef000
#define SGDMA_MM2ST_M_READ_HPS_0_L2_SPAN 4096
#define SGDMA_MM2ST_M_READ_HPS_0_L2_END 0xfffeffff

/*
 * Macros for device 'hps_0_axi_ocram', class 'axi_ocram'
 * Path to the device is from the master group 'sgdma_mm2st_m_read'.
 * The macros are prefixed with 'SGDMA_MM2ST_M_READ_HPS_0_AXI_OCRAM_'.
 * The prefix is the master group descriptor and the slave descriptor.
 */
#define SGDMA_MM2ST_M_READ_HPS_0_AXI_OCRAM_COMPONENT_TYPE axi_ocram
#define SGDMA_MM2ST_M_READ_HPS_0_AXI_OCRAM_COMPONENT_NAME hps_0_axi_ocram
#define SGDMA_MM2ST_M_READ_HPS_0_AXI_OCRAM_BASE 0xffff0000
#define SGDMA_MM2ST_M_READ_HPS_0_AXI_OCRAM_SPAN 65536
#define SGDMA_MM2ST_M_READ_HPS_0_AXI_OCRAM_END 0xffffffff
#define SGDMA_MM2ST_M_READ_HPS_0_AXI_OCRAM_SIZE_MULTIPLE 1
#define SGDMA_MM2ST_M_READ_HPS_0_AXI_OCRAM_SIZE_VALUE 1<<16
#define SGDMA_MM2ST_M_READ_HPS_0_AXI_OCRAM_WRITABLE 1
#define SGDMA_MM2ST_M_READ_HPS_0_AXI_OCRAM_MEMORY_INFO_GENERATE_DAT_SYM 0
#define SGDMA_MM2ST_M_READ_HPS_0_AXI_OCRAM_MEMORY_INFO_GENERATE_HEX 0
#define SGDMA_MM2ST_M_READ_HPS_0_AXI_OCRAM_MEMORY_INFO_MEM_INIT_DATA_WIDTH 16

/*
 * Macros for device 'sgdma_st2mm', class 'altera_avalon_sgdma'
 * The macros are prefixed with 'SGDMA_ST2MM_'.
 * The prefix is the slave descriptor.
 */
#define SGDMA_ST2MM_COMPONENT_TYPE altera_avalon_sgdma
#define SGDMA_ST2MM_COMPONENT_NAME sgdma_st2mm
#define SGDMA_ST2MM_BASE 0x20040
#define SGDMA_ST2MM_SPAN 64
#define SGDMA_ST2MM_END 0x2007f
#define SGDMA_ST2MM_ADDRESS_WIDTH 32
#define SGDMA_ST2MM_ALWAYS_DO_MAX_BURST 1
#define SGDMA_ST2MM_ATLANTIC_CHANNEL_DATA_WIDTH 4
#define SGDMA_ST2MM_AVALON_MM_BYTE_REORDER_MODE 0
#define SGDMA_ST2MM_BURST_DATA_WIDTH 8
#define SGDMA_ST2MM_BURST_TRANSFER 0
#define SGDMA_ST2MM_BYTES_TO_TRANSFER_DATA_WIDTH 16
#define SGDMA_ST2MM_CHAIN_WRITEBACK_DATA_WIDTH 32
#define SGDMA_ST2MM_COMMAND_FIFO_DATA_WIDTH 104
#define SGDMA_ST2MM_CONTROL_DATA_WIDTH 8
#define SGDMA_ST2MM_CONTROL_SLAVE_ADDRESS_WIDTH 4
#define SGDMA_ST2MM_CONTROL_SLAVE_DATA_WIDTH 32
#define SGDMA_ST2MM_DESCRIPTOR_READ_BURST 0
#define SGDMA_ST2MM_DESC_DATA_WIDTH 32
#define SGDMA_ST2MM_HAS_READ_BLOCK 0
#define SGDMA_ST2MM_HAS_WRITE_BLOCK 1
#define SGDMA_ST2MM_IN_ERROR_WIDTH 0
#define SGDMA_ST2MM_OUT_ERROR_WIDTH 0
#define SGDMA_ST2MM_READ_BLOCK_DATA_WIDTH 16
#define SGDMA_ST2MM_READ_BURSTCOUNT_WIDTH 4
#define SGDMA_ST2MM_STATUS_TOKEN_DATA_WIDTH 24
#define SGDMA_ST2MM_STREAM_DATA_WIDTH 16
#define SGDMA_ST2MM_SYMBOLS_PER_BEAT 2
#define SGDMA_ST2MM_UNALIGNED_TRANSFER 0
#define SGDMA_ST2MM_WRITE_BLOCK_DATA_WIDTH 16
#define SGDMA_ST2MM_WRITE_BURSTCOUNT_WIDTH 4

/*
 * Macros for device 'hps_0_axi_sdram', class 'axi_sdram'
 * Path to the device is from the master group 'sgdma_st2mm_m_write'.
 * The macros are prefixed with 'SGDMA_ST2MM_M_WRITE_HPS_0_AXI_SDRAM_'.
 * The prefix is the master group descriptor and the slave descriptor.
 */
#define SGDMA_ST2MM_M_WRITE_HPS_0_AXI_SDRAM_COMPONENT_TYPE axi_sdram
#define SGDMA_ST2MM_M_WRITE_HPS_0_AXI_SDRAM_COMPONENT_NAME hps_0_axi_sdram
#define SGDMA_ST2MM_M_WRITE_HPS_0_AXI_SDRAM_BASE 0x0
#define SGDMA_ST2MM_M_WRITE_HPS_0_AXI_SDRAM_SPAN 0x80000000
#define SGDMA_ST2MM_M_WRITE_HPS_0_AXI_SDRAM_END 0x7fffffff
#define SGDMA_ST2MM_M_WRITE_HPS_0_AXI_SDRAM_SIZE_MULTIPLE 1
#define SGDMA_ST2MM_M_WRITE_HPS_0_AXI_SDRAM_SIZE_VALUE 1<<31
#define SGDMA_ST2MM_M_WRITE_HPS_0_AXI_SDRAM_WRITABLE 1
#define SGDMA_ST2MM_M_WRITE_HPS_0_AXI_SDRAM_MEMORY_INFO_GENERATE_DAT_SYM 0
#define SGDMA_ST2MM_M_WRITE_HPS_0_AXI_SDRAM_MEMORY_INFO_GENERATE_HEX 0
#define SGDMA_ST2MM_M_WRITE_HPS_0_AXI_SDRAM_MEMORY_INFO_MEM_INIT_DATA_WIDTH 31

/*
 * Macros for device 'hps_0_gmac0', class 'stmmac'
 * Path to the device is from the master group 'sgdma_st2mm_m_write'.
 * The macros are prefixed with 'SGDMA_ST2MM_M_WRITE_HPS_0_GMAC0_'.
 * The prefix is the master group descriptor and the slave descriptor.
 */
#define SGDMA_ST2MM_M_WRITE_HPS_0_GMAC0_COMPONENT_TYPE stmmac
#define SGDMA_ST2MM_M_WRITE_HPS_0_GMAC0_COMPONENT_NAME hps_0_gmac0
#define SGDMA_ST2MM_M_WRITE_HPS_0_GMAC0_BASE 0xff700000
#define SGDMA_ST2MM_M_WRITE_HPS_0_GMAC0_SPAN 8192
#define SGDMA_ST2MM_M_WRITE_HPS_0_GMAC0_END 0xff701fff

/*
 * Macros for device 'hps_0_gmac1', class 'stmmac'
 * Path to the device is from the master group 'sgdma_st2mm_m_write'.
 * The macros are prefixed with 'SGDMA_ST2MM_M_WRITE_HPS_0_GMAC1_'.
 * The prefix is the master group descriptor and the slave descriptor.
 */
#define SGDMA_ST2MM_M_WRITE_HPS_0_GMAC1_COMPONENT_TYPE stmmac
#define SGDMA_ST2MM_M_WRITE_HPS_0_GMAC1_COMPONENT_NAME hps_0_gmac1
#define SGDMA_ST2MM_M_WRITE_HPS_0_GMAC1_BASE 0xff702000
#define SGDMA_ST2MM_M_WRITE_HPS_0_GMAC1_SPAN 8192
#define SGDMA_ST2MM_M_WRITE_HPS_0_GMAC1_END 0xff703fff

/*
 * Macros for device 'hps_0_sdmmc', class 'sdmmc'
 * Path to the device is from the master group 'sgdma_st2mm_m_write'.
 * The macros are prefixed with 'SGDMA_ST2MM_M_WRITE_HPS_0_SDMMC_'.
 * The prefix is the master group descriptor and the slave descriptor.
 */
#define SGDMA_ST2MM_M_WRITE_HPS_0_SDMMC_COMPONENT_TYPE sdmmc
#define SGDMA_ST2MM_M_WRITE_HPS_0_SDMMC_COMPONENT_NAME hps_0_sdmmc
#define SGDMA_ST2MM_M_WRITE_HPS_0_SDMMC_BASE 0xff704000
#define SGDMA_ST2MM_M_WRITE_HPS_0_SDMMC_SPAN 4096
#define SGDMA_ST2MM_M_WRITE_HPS_0_SDMMC_END 0xff704fff

/*
 * Macros for device 'hps_0_qspi', class 'cadence_qspi'
 * Path to the device is from the master group 'sgdma_st2mm_m_write'.
 * The macros are prefixed with 'SGDMA_ST2MM_M_WRITE_HPS_0_QSPI_'.
 * The prefix is the master group descriptor and the slave descriptor.
 */
#define SGDMA_ST2MM_M_WRITE_HPS_0_QSPI_COMPONENT_TYPE cadence_qspi
#define SGDMA_ST2MM_M_WRITE_HPS_0_QSPI_COMPONENT_NAME hps_0_qspi
#define SGDMA_ST2MM_M_WRITE_HPS_0_QSPI_BASE 0xff705000
#define SGDMA_ST2MM_M_WRITE_HPS_0_QSPI_SPAN 256
#define SGDMA_ST2MM_M_WRITE_HPS_0_QSPI_END 0xff7050ff

/*
 * Macros for device 'hps_0_fpgamgr', class 'altera_fpgamgr'
 * Path to the device is from the master group 'sgdma_st2mm_m_write'.
 * The macros are prefixed with 'SGDMA_ST2MM_M_WRITE_HPS_0_FPGAMGR_'.
 * The prefix is the master group descriptor and the slave descriptor.
 */
#define SGDMA_ST2MM_M_WRITE_HPS_0_FPGAMGR_COMPONENT_TYPE altera_fpgamgr
#define SGDMA_ST2MM_M_WRITE_HPS_0_FPGAMGR_COMPONENT_NAME hps_0_fpgamgr
#define SGDMA_ST2MM_M_WRITE_HPS_0_FPGAMGR_BASE 0xff706000
#define SGDMA_ST2MM_M_WRITE_HPS_0_FPGAMGR_SPAN 4096
#define SGDMA_ST2MM_M_WRITE_HPS_0_FPGAMGR_END 0xff706fff

/*
 * Macros for device 'hps_0_gpio0', class 'dw_gpio'
 * Path to the device is from the master group 'sgdma_st2mm_m_write'.
 * The macros are prefixed with 'SGDMA_ST2MM_M_WRITE_HPS_0_GPIO0_'.
 * The prefix is the master group descriptor and the slave descriptor.
 */
#define SGDMA_ST2MM_M_WRITE_HPS_0_GPIO0_COMPONENT_TYPE dw_gpio
#define SGDMA_ST2MM_M_WRITE_HPS_0_GPIO0_COMPONENT_NAME hps_0_gpio0
#define SGDMA_ST2MM_M_WRITE_HPS_0_GPIO0_BASE 0xff708000
#define SGDMA_ST2MM_M_WRITE_HPS_0_GPIO0_SPAN 256
#define SGDMA_ST2MM_M_WRITE_HPS_0_GPIO0_END 0xff7080ff

/*
 * Macros for device 'hps_0_gpio1', class 'dw_gpio'
 * Path to the device is from the master group 'sgdma_st2mm_m_write'.
 * The macros are prefixed with 'SGDMA_ST2MM_M_WRITE_HPS_0_GPIO1_'.
 * The prefix is the master group descriptor and the slave descriptor.
 */
#define SGDMA_ST2MM_M_WRITE_HPS_0_GPIO1_COMPONENT_TYPE dw_gpio
#define SGDMA_ST2MM_M_WRITE_HPS_0_GPIO1_COMPONENT_NAME hps_0_gpio1
#define SGDMA_ST2MM_M_WRITE_HPS_0_GPIO1_BASE 0xff709000
#define SGDMA_ST2MM_M_WRITE_HPS_0_GPIO1_SPAN 256
#define SGDMA_ST2MM_M_WRITE_HPS_0_GPIO1_END 0xff7090ff

/*
 * Macros for device 'hps_0_gpio2', class 'dw_gpio'
 * Path to the device is from the master group 'sgdma_st2mm_m_write'.
 * The macros are prefixed with 'SGDMA_ST2MM_M_WRITE_HPS_0_GPIO2_'.
 * The prefix is the master group descriptor and the slave descriptor.
 */
#define SGDMA_ST2MM_M_WRITE_HPS_0_GPIO2_COMPONENT_TYPE dw_gpio
#define SGDMA_ST2MM_M_WRITE_HPS_0_GPIO2_COMPONENT_NAME hps_0_gpio2
#define SGDMA_ST2MM_M_WRITE_HPS_0_GPIO2_BASE 0xff70a000
#define SGDMA_ST2MM_M_WRITE_HPS_0_GPIO2_SPAN 256
#define SGDMA_ST2MM_M_WRITE_HPS_0_GPIO2_END 0xff70a0ff

/*
 * Macros for device 'hps_0_l3regs', class 'altera_l3regs'
 * Path to the device is from the master group 'sgdma_st2mm_m_write'.
 * The macros are prefixed with 'SGDMA_ST2MM_M_WRITE_HPS_0_L3REGS_'.
 * The prefix is the master group descriptor and the slave descriptor.
 */
#define SGDMA_ST2MM_M_WRITE_HPS_0_L3REGS_COMPONENT_TYPE altera_l3regs
#define SGDMA_ST2MM_M_WRITE_HPS_0_L3REGS_COMPONENT_NAME hps_0_l3regs
#define SGDMA_ST2MM_M_WRITE_HPS_0_L3REGS_BASE 0xff800000
#define SGDMA_ST2MM_M_WRITE_HPS_0_L3REGS_SPAN 4096
#define SGDMA_ST2MM_M_WRITE_HPS_0_L3REGS_END 0xff800fff

/*
 * Macros for device 'hps_0_nand0', class 'denali_nand'
 * Path to the device is from the master group 'sgdma_st2mm_m_write'.
 * The macros are prefixed with 'SGDMA_ST2MM_M_WRITE_HPS_0_NAND0_'.
 * The prefix is the master group descriptor and the slave descriptor.
 */
#define SGDMA_ST2MM_M_WRITE_HPS_0_NAND0_COMPONENT_TYPE denali_nand
#define SGDMA_ST2MM_M_WRITE_HPS_0_NAND0_COMPONENT_NAME hps_0_nand0
#define SGDMA_ST2MM_M_WRITE_HPS_0_NAND0_BASE 0xff900000
#define SGDMA_ST2MM_M_WRITE_HPS_0_NAND0_SPAN 65536
#define SGDMA_ST2MM_M_WRITE_HPS_0_NAND0_END 0xff90ffff

/*
 * Macros for device 'hps_0_usb0', class 'usb'
 * Path to the device is from the master group 'sgdma_st2mm_m_write'.
 * The macros are prefixed with 'SGDMA_ST2MM_M_WRITE_HPS_0_USB0_'.
 * The prefix is the master group descriptor and the slave descriptor.
 */
#define SGDMA_ST2MM_M_WRITE_HPS_0_USB0_COMPONENT_TYPE usb
#define SGDMA_ST2MM_M_WRITE_HPS_0_USB0_COMPONENT_NAME hps_0_usb0
#define SGDMA_ST2MM_M_WRITE_HPS_0_USB0_BASE 0xffb00000
#define SGDMA_ST2MM_M_WRITE_HPS_0_USB0_SPAN 262144
#define SGDMA_ST2MM_M_WRITE_HPS_0_USB0_END 0xffb3ffff

/*
 * Macros for device 'hps_0_usb1', class 'usb'
 * Path to the device is from the master group 'sgdma_st2mm_m_write'.
 * The macros are prefixed with 'SGDMA_ST2MM_M_WRITE_HPS_0_USB1_'.
 * The prefix is the master group descriptor and the slave descriptor.
 */
#define SGDMA_ST2MM_M_WRITE_HPS_0_USB1_COMPONENT_TYPE usb
#define SGDMA_ST2MM_M_WRITE_HPS_0_USB1_COMPONENT_NAME hps_0_usb1
#define SGDMA_ST2MM_M_WRITE_HPS_0_USB1_BASE 0xffb40000
#define SGDMA_ST2MM_M_WRITE_HPS_0_USB1_SPAN 262144
#define SGDMA_ST2MM_M_WRITE_HPS_0_USB1_END 0xffb7ffff

/*
 * Macros for device 'hps_0_dcan0', class 'bosch_dcan'
 * Path to the device is from the master group 'sgdma_st2mm_m_write'.
 * The macros are prefixed with 'SGDMA_ST2MM_M_WRITE_HPS_0_DCAN0_'.
 * The prefix is the master group descriptor and the slave descriptor.
 */
#define SGDMA_ST2MM_M_WRITE_HPS_0_DCAN0_COMPONENT_TYPE bosch_dcan
#define SGDMA_ST2MM_M_WRITE_HPS_0_DCAN0_COMPONENT_NAME hps_0_dcan0
#define SGDMA_ST2MM_M_WRITE_HPS_0_DCAN0_BASE 0xffc00000
#define SGDMA_ST2MM_M_WRITE_HPS_0_DCAN0_SPAN 4096
#define SGDMA_ST2MM_M_WRITE_HPS_0_DCAN0_END 0xffc00fff

/*
 * Macros for device 'hps_0_dcan1', class 'bosch_dcan'
 * Path to the device is from the master group 'sgdma_st2mm_m_write'.
 * The macros are prefixed with 'SGDMA_ST2MM_M_WRITE_HPS_0_DCAN1_'.
 * The prefix is the master group descriptor and the slave descriptor.
 */
#define SGDMA_ST2MM_M_WRITE_HPS_0_DCAN1_COMPONENT_TYPE bosch_dcan
#define SGDMA_ST2MM_M_WRITE_HPS_0_DCAN1_COMPONENT_NAME hps_0_dcan1
#define SGDMA_ST2MM_M_WRITE_HPS_0_DCAN1_BASE 0xffc01000
#define SGDMA_ST2MM_M_WRITE_HPS_0_DCAN1_SPAN 4096
#define SGDMA_ST2MM_M_WRITE_HPS_0_DCAN1_END 0xffc01fff

/*
 * Macros for device 'hps_0_uart0', class 'snps_uart'
 * Path to the device is from the master group 'sgdma_st2mm_m_write'.
 * The macros are prefixed with 'SGDMA_ST2MM_M_WRITE_HPS_0_UART0_'.
 * The prefix is the master group descriptor and the slave descriptor.
 */
#define SGDMA_ST2MM_M_WRITE_HPS_0_UART0_COMPONENT_TYPE snps_uart
#define SGDMA_ST2MM_M_WRITE_HPS_0_UART0_COMPONENT_NAME hps_0_uart0
#define SGDMA_ST2MM_M_WRITE_HPS_0_UART0_BASE 0xffc02000
#define SGDMA_ST2MM_M_WRITE_HPS_0_UART0_SPAN 256
#define SGDMA_ST2MM_M_WRITE_HPS_0_UART0_END 0xffc020ff
#define SGDMA_ST2MM_M_WRITE_HPS_0_UART0_FIFO_DEPTH 128
#define SGDMA_ST2MM_M_WRITE_HPS_0_UART0_FIFO_HWFC 0
#define SGDMA_ST2MM_M_WRITE_HPS_0_UART0_FIFO_MODE 1
#define SGDMA_ST2MM_M_WRITE_HPS_0_UART0_FIFO_SWFC 0
#define SGDMA_ST2MM_M_WRITE_HPS_0_UART0_FREQ 100000000

/*
 * Macros for device 'hps_0_uart1', class 'snps_uart'
 * Path to the device is from the master group 'sgdma_st2mm_m_write'.
 * The macros are prefixed with 'SGDMA_ST2MM_M_WRITE_HPS_0_UART1_'.
 * The prefix is the master group descriptor and the slave descriptor.
 */
#define SGDMA_ST2MM_M_WRITE_HPS_0_UART1_COMPONENT_TYPE snps_uart
#define SGDMA_ST2MM_M_WRITE_HPS_0_UART1_COMPONENT_NAME hps_0_uart1
#define SGDMA_ST2MM_M_WRITE_HPS_0_UART1_BASE 0xffc03000
#define SGDMA_ST2MM_M_WRITE_HPS_0_UART1_SPAN 256
#define SGDMA_ST2MM_M_WRITE_HPS_0_UART1_END 0xffc030ff
#define SGDMA_ST2MM_M_WRITE_HPS_0_UART1_FIFO_DEPTH 128
#define SGDMA_ST2MM_M_WRITE_HPS_0_UART1_FIFO_HWFC 0
#define SGDMA_ST2MM_M_WRITE_HPS_0_UART1_FIFO_MODE 1
#define SGDMA_ST2MM_M_WRITE_HPS_0_UART1_FIFO_SWFC 0
#define SGDMA_ST2MM_M_WRITE_HPS_0_UART1_FREQ 100000000

/*
 * Macros for device 'hps_0_i2c0', class 'designware_i2c'
 * Path to the device is from the master group 'sgdma_st2mm_m_write'.
 * The macros are prefixed with 'SGDMA_ST2MM_M_WRITE_HPS_0_I2C0_'.
 * The prefix is the master group descriptor and the slave descriptor.
 */
#define SGDMA_ST2MM_M_WRITE_HPS_0_I2C0_COMPONENT_TYPE designware_i2c
#define SGDMA_ST2MM_M_WRITE_HPS_0_I2C0_COMPONENT_NAME hps_0_i2c0
#define SGDMA_ST2MM_M_WRITE_HPS_0_I2C0_BASE 0xffc04000
#define SGDMA_ST2MM_M_WRITE_HPS_0_I2C0_SPAN 256
#define SGDMA_ST2MM_M_WRITE_HPS_0_I2C0_END 0xffc040ff

/*
 * Macros for device 'hps_0_i2c1', class 'designware_i2c'
 * Path to the device is from the master group 'sgdma_st2mm_m_write'.
 * The macros are prefixed with 'SGDMA_ST2MM_M_WRITE_HPS_0_I2C1_'.
 * The prefix is the master group descriptor and the slave descriptor.
 */
#define SGDMA_ST2MM_M_WRITE_HPS_0_I2C1_COMPONENT_TYPE designware_i2c
#define SGDMA_ST2MM_M_WRITE_HPS_0_I2C1_COMPONENT_NAME hps_0_i2c1
#define SGDMA_ST2MM_M_WRITE_HPS_0_I2C1_BASE 0xffc05000
#define SGDMA_ST2MM_M_WRITE_HPS_0_I2C1_SPAN 256
#define SGDMA_ST2MM_M_WRITE_HPS_0_I2C1_END 0xffc050ff

/*
 * Macros for device 'hps_0_i2c2', class 'designware_i2c'
 * Path to the device is from the master group 'sgdma_st2mm_m_write'.
 * The macros are prefixed with 'SGDMA_ST2MM_M_WRITE_HPS_0_I2C2_'.
 * The prefix is the master group descriptor and the slave descriptor.
 */
#define SGDMA_ST2MM_M_WRITE_HPS_0_I2C2_COMPONENT_TYPE designware_i2c
#define SGDMA_ST2MM_M_WRITE_HPS_0_I2C2_COMPONENT_NAME hps_0_i2c2
#define SGDMA_ST2MM_M_WRITE_HPS_0_I2C2_BASE 0xffc06000
#define SGDMA_ST2MM_M_WRITE_HPS_0_I2C2_SPAN 256
#define SGDMA_ST2MM_M_WRITE_HPS_0_I2C2_END 0xffc060ff

/*
 * Macros for device 'hps_0_i2c3', class 'designware_i2c'
 * Path to the device is from the master group 'sgdma_st2mm_m_write'.
 * The macros are prefixed with 'SGDMA_ST2MM_M_WRITE_HPS_0_I2C3_'.
 * The prefix is the master group descriptor and the slave descriptor.
 */
#define SGDMA_ST2MM_M_WRITE_HPS_0_I2C3_COMPONENT_TYPE designware_i2c
#define SGDMA_ST2MM_M_WRITE_HPS_0_I2C3_COMPONENT_NAME hps_0_i2c3
#define SGDMA_ST2MM_M_WRITE_HPS_0_I2C3_BASE 0xffc07000
#define SGDMA_ST2MM_M_WRITE_HPS_0_I2C3_SPAN 256
#define SGDMA_ST2MM_M_WRITE_HPS_0_I2C3_END 0xffc070ff

/*
 * Macros for device 'hps_0_timer0', class 'dw_apb_timer_sp'
 * Path to the device is from the master group 'sgdma_st2mm_m_write'.
 * The macros are prefixed with 'SGDMA_ST2MM_M_WRITE_HPS_0_TIMER0_'.
 * The prefix is the master group descriptor and the slave descriptor.
 */
#define SGDMA_ST2MM_M_WRITE_HPS_0_TIMER0_COMPONENT_TYPE dw_apb_timer_sp
#define SGDMA_ST2MM_M_WRITE_HPS_0_TIMER0_COMPONENT_NAME hps_0_timer0
#define SGDMA_ST2MM_M_WRITE_HPS_0_TIMER0_BASE 0xffc08000
#define SGDMA_ST2MM_M_WRITE_HPS_0_TIMER0_SPAN 256
#define SGDMA_ST2MM_M_WRITE_HPS_0_TIMER0_END 0xffc080ff

/*
 * Macros for device 'hps_0_timer1', class 'dw_apb_timer_sp'
 * Path to the device is from the master group 'sgdma_st2mm_m_write'.
 * The macros are prefixed with 'SGDMA_ST2MM_M_WRITE_HPS_0_TIMER1_'.
 * The prefix is the master group descriptor and the slave descriptor.
 */
#define SGDMA_ST2MM_M_WRITE_HPS_0_TIMER1_COMPONENT_TYPE dw_apb_timer_sp
#define SGDMA_ST2MM_M_WRITE_HPS_0_TIMER1_COMPONENT_NAME hps_0_timer1
#define SGDMA_ST2MM_M_WRITE_HPS_0_TIMER1_BASE 0xffc09000
#define SGDMA_ST2MM_M_WRITE_HPS_0_TIMER1_SPAN 256
#define SGDMA_ST2MM_M_WRITE_HPS_0_TIMER1_END 0xffc090ff

/*
 * Macros for device 'hps_0_sdrctl', class 'altera_sdrctl'
 * Path to the device is from the master group 'sgdma_st2mm_m_write'.
 * The macros are prefixed with 'SGDMA_ST2MM_M_WRITE_HPS_0_SDRCTL_'.
 * The prefix is the master group descriptor and the slave descriptor.
 */
#define SGDMA_ST2MM_M_WRITE_HPS_0_SDRCTL_COMPONENT_TYPE altera_sdrctl
#define SGDMA_ST2MM_M_WRITE_HPS_0_SDRCTL_COMPONENT_NAME hps_0_sdrctl
#define SGDMA_ST2MM_M_WRITE_HPS_0_SDRCTL_BASE 0xffc25000
#define SGDMA_ST2MM_M_WRITE_HPS_0_SDRCTL_SPAN 4096
#define SGDMA_ST2MM_M_WRITE_HPS_0_SDRCTL_END 0xffc25fff

/*
 * Macros for device 'hps_0_timer2', class 'dw_apb_timer_osc'
 * Path to the device is from the master group 'sgdma_st2mm_m_write'.
 * The macros are prefixed with 'SGDMA_ST2MM_M_WRITE_HPS_0_TIMER2_'.
 * The prefix is the master group descriptor and the slave descriptor.
 */
#define SGDMA_ST2MM_M_WRITE_HPS_0_TIMER2_COMPONENT_TYPE dw_apb_timer_osc
#define SGDMA_ST2MM_M_WRITE_HPS_0_TIMER2_COMPONENT_NAME hps_0_timer2
#define SGDMA_ST2MM_M_WRITE_HPS_0_TIMER2_BASE 0xffd00000
#define SGDMA_ST2MM_M_WRITE_HPS_0_TIMER2_SPAN 256
#define SGDMA_ST2MM_M_WRITE_HPS_0_TIMER2_END 0xffd000ff

/*
 * Macros for device 'hps_0_timer3', class 'dw_apb_timer_osc'
 * Path to the device is from the master group 'sgdma_st2mm_m_write'.
 * The macros are prefixed with 'SGDMA_ST2MM_M_WRITE_HPS_0_TIMER3_'.
 * The prefix is the master group descriptor and the slave descriptor.
 */
#define SGDMA_ST2MM_M_WRITE_HPS_0_TIMER3_COMPONENT_TYPE dw_apb_timer_osc
#define SGDMA_ST2MM_M_WRITE_HPS_0_TIMER3_COMPONENT_NAME hps_0_timer3
#define SGDMA_ST2MM_M_WRITE_HPS_0_TIMER3_BASE 0xffd01000
#define SGDMA_ST2MM_M_WRITE_HPS_0_TIMER3_SPAN 256
#define SGDMA_ST2MM_M_WRITE_HPS_0_TIMER3_END 0xffd010ff

/*
 * Macros for device 'hps_0_clkmgr', class 'asimov_clkmgr'
 * Path to the device is from the master group 'sgdma_st2mm_m_write'.
 * The macros are prefixed with 'SGDMA_ST2MM_M_WRITE_HPS_0_CLKMGR_'.
 * The prefix is the master group descriptor and the slave descriptor.
 */
#define SGDMA_ST2MM_M_WRITE_HPS_0_CLKMGR_COMPONENT_TYPE asimov_clkmgr
#define SGDMA_ST2MM_M_WRITE_HPS_0_CLKMGR_COMPONENT_NAME hps_0_clkmgr
#define SGDMA_ST2MM_M_WRITE_HPS_0_CLKMGR_BASE 0xffd04000
#define SGDMA_ST2MM_M_WRITE_HPS_0_CLKMGR_SPAN 4096
#define SGDMA_ST2MM_M_WRITE_HPS_0_CLKMGR_END 0xffd04fff

/*
 * Macros for device 'hps_0_rstmgr', class 'altera_rstmgr'
 * Path to the device is from the master group 'sgdma_st2mm_m_write'.
 * The macros are prefixed with 'SGDMA_ST2MM_M_WRITE_HPS_0_RSTMGR_'.
 * The prefix is the master group descriptor and the slave descriptor.
 */
#define SGDMA_ST2MM_M_WRITE_HPS_0_RSTMGR_COMPONENT_TYPE altera_rstmgr
#define SGDMA_ST2MM_M_WRITE_HPS_0_RSTMGR_COMPONENT_NAME hps_0_rstmgr
#define SGDMA_ST2MM_M_WRITE_HPS_0_RSTMGR_BASE 0xffd05000
#define SGDMA_ST2MM_M_WRITE_HPS_0_RSTMGR_SPAN 256
#define SGDMA_ST2MM_M_WRITE_HPS_0_RSTMGR_END 0xffd050ff

/*
 * Macros for device 'hps_0_sysmgr', class 'altera_sysmgr'
 * Path to the device is from the master group 'sgdma_st2mm_m_write'.
 * The macros are prefixed with 'SGDMA_ST2MM_M_WRITE_HPS_0_SYSMGR_'.
 * The prefix is the master group descriptor and the slave descriptor.
 */
#define SGDMA_ST2MM_M_WRITE_HPS_0_SYSMGR_COMPONENT_TYPE altera_sysmgr
#define SGDMA_ST2MM_M_WRITE_HPS_0_SYSMGR_COMPONENT_NAME hps_0_sysmgr
#define SGDMA_ST2MM_M_WRITE_HPS_0_SYSMGR_BASE 0xffd08000
#define SGDMA_ST2MM_M_WRITE_HPS_0_SYSMGR_SPAN 1024
#define SGDMA_ST2MM_M_WRITE_HPS_0_SYSMGR_END 0xffd083ff

/*
 * Macros for device 'hps_0_dma', class 'arm_pl330_dma'
 * Path to the device is from the master group 'sgdma_st2mm_m_write'.
 * The macros are prefixed with 'SGDMA_ST2MM_M_WRITE_HPS_0_DMA_'.
 * The prefix is the master group descriptor and the slave descriptor.
 */
#define SGDMA_ST2MM_M_WRITE_HPS_0_DMA_COMPONENT_TYPE arm_pl330_dma
#define SGDMA_ST2MM_M_WRITE_HPS_0_DMA_COMPONENT_NAME hps_0_dma
#define SGDMA_ST2MM_M_WRITE_HPS_0_DMA_BASE 0xffe01000
#define SGDMA_ST2MM_M_WRITE_HPS_0_DMA_SPAN 4096
#define SGDMA_ST2MM_M_WRITE_HPS_0_DMA_END 0xffe01fff

/*
 * Macros for device 'hps_0_spim0', class 'spi'
 * Path to the device is from the master group 'sgdma_st2mm_m_write'.
 * The macros are prefixed with 'SGDMA_ST2MM_M_WRITE_HPS_0_SPIM0_'.
 * The prefix is the master group descriptor and the slave descriptor.
 */
#define SGDMA_ST2MM_M_WRITE_HPS_0_SPIM0_COMPONENT_TYPE spi
#define SGDMA_ST2MM_M_WRITE_HPS_0_SPIM0_COMPONENT_NAME hps_0_spim0
#define SGDMA_ST2MM_M_WRITE_HPS_0_SPIM0_BASE 0xfff00000
#define SGDMA_ST2MM_M_WRITE_HPS_0_SPIM0_SPAN 256
#define SGDMA_ST2MM_M_WRITE_HPS_0_SPIM0_END 0xfff000ff

/*
 * Macros for device 'hps_0_spim1', class 'spi'
 * Path to the device is from the master group 'sgdma_st2mm_m_write'.
 * The macros are prefixed with 'SGDMA_ST2MM_M_WRITE_HPS_0_SPIM1_'.
 * The prefix is the master group descriptor and the slave descriptor.
 */
#define SGDMA_ST2MM_M_WRITE_HPS_0_SPIM1_COMPONENT_TYPE spi
#define SGDMA_ST2MM_M_WRITE_HPS_0_SPIM1_COMPONENT_NAME hps_0_spim1
#define SGDMA_ST2MM_M_WRITE_HPS_0_SPIM1_BASE 0xfff01000
#define SGDMA_ST2MM_M_WRITE_HPS_0_SPIM1_SPAN 256
#define SGDMA_ST2MM_M_WRITE_HPS_0_SPIM1_END 0xfff010ff

/*
 * Macros for device 'hps_0_timer', class 'arm_internal_timer'
 * Path to the device is from the master group 'sgdma_st2mm_m_write'.
 * The macros are prefixed with 'SGDMA_ST2MM_M_WRITE_HPS_0_TIMER_'.
 * The prefix is the master group descriptor and the slave descriptor.
 */
#define SGDMA_ST2MM_M_WRITE_HPS_0_TIMER_COMPONENT_TYPE arm_internal_timer
#define SGDMA_ST2MM_M_WRITE_HPS_0_TIMER_COMPONENT_NAME hps_0_timer
#define SGDMA_ST2MM_M_WRITE_HPS_0_TIMER_BASE 0xfffec600
#define SGDMA_ST2MM_M_WRITE_HPS_0_TIMER_SPAN 256
#define SGDMA_ST2MM_M_WRITE_HPS_0_TIMER_END 0xfffec6ff

/*
 * Macros for device 'hps_0_arm_gic_0', class 'arm_gic'
 * Path to the device is from the master group 'sgdma_st2mm_m_write'.
 * The macros are prefixed with 'SGDMA_ST2MM_M_WRITE_HPS_0_ARM_GIC_0_'.
 * The prefix is the master group descriptor and the slave descriptor.
 */
#define SGDMA_ST2MM_M_WRITE_HPS_0_ARM_GIC_0_COMPONENT_TYPE arm_gic
#define SGDMA_ST2MM_M_WRITE_HPS_0_ARM_GIC_0_COMPONENT_NAME hps_0_arm_gic_0
#define SGDMA_ST2MM_M_WRITE_HPS_0_ARM_GIC_0_BASE 0xfffed000
#define SGDMA_ST2MM_M_WRITE_HPS_0_ARM_GIC_0_SPAN 4096
#define SGDMA_ST2MM_M_WRITE_HPS_0_ARM_GIC_0_END 0xfffedfff

/*
 * Macros for device 'hps_0_L2', class 'arm_pl310_L2'
 * Path to the device is from the master group 'sgdma_st2mm_m_write'.
 * The macros are prefixed with 'SGDMA_ST2MM_M_WRITE_HPS_0_L2_'.
 * The prefix is the master group descriptor and the slave descriptor.
 */
#define SGDMA_ST2MM_M_WRITE_HPS_0_L2_COMPONENT_TYPE arm_pl310_L2
#define SGDMA_ST2MM_M_WRITE_HPS_0_L2_COMPONENT_NAME hps_0_L2
#define SGDMA_ST2MM_M_WRITE_HPS_0_L2_BASE 0xfffef000
#define SGDMA_ST2MM_M_WRITE_HPS_0_L2_SPAN 4096
#define SGDMA_ST2MM_M_WRITE_HPS_0_L2_END 0xfffeffff

/*
 * Macros for device 'hps_0_axi_ocram', class 'axi_ocram'
 * Path to the device is from the master group 'sgdma_st2mm_m_write'.
 * The macros are prefixed with 'SGDMA_ST2MM_M_WRITE_HPS_0_AXI_OCRAM_'.
 * The prefix is the master group descriptor and the slave descriptor.
 */
#define SGDMA_ST2MM_M_WRITE_HPS_0_AXI_OCRAM_COMPONENT_TYPE axi_ocram
#define SGDMA_ST2MM_M_WRITE_HPS_0_AXI_OCRAM_COMPONENT_NAME hps_0_axi_ocram
#define SGDMA_ST2MM_M_WRITE_HPS_0_AXI_OCRAM_BASE 0xffff0000
#define SGDMA_ST2MM_M_WRITE_HPS_0_AXI_OCRAM_SPAN 65536
#define SGDMA_ST2MM_M_WRITE_HPS_0_AXI_OCRAM_END 0xffffffff
#define SGDMA_ST2MM_M_WRITE_HPS_0_AXI_OCRAM_SIZE_MULTIPLE 1
#define SGDMA_ST2MM_M_WRITE_HPS_0_AXI_OCRAM_SIZE_VALUE 1<<16
#define SGDMA_ST2MM_M_WRITE_HPS_0_AXI_OCRAM_WRITABLE 1
#define SGDMA_ST2MM_M_WRITE_HPS_0_AXI_OCRAM_MEMORY_INFO_GENERATE_DAT_SYM 0
#define SGDMA_ST2MM_M_WRITE_HPS_0_AXI_OCRAM_MEMORY_INFO_GENERATE_HEX 0
#define SGDMA_ST2MM_M_WRITE_HPS_0_AXI_OCRAM_MEMORY_INFO_MEM_INIT_DATA_WIDTH 16

/*
 * Macros for device 'fifo_in', class 'altera_avalon_sc_fifo'
 * The macros are prefixed with 'FIFO_IN_'.
 * The prefix is the slave descriptor.
 */
#define FIFO_IN_COMPONENT_TYPE altera_avalon_sc_fifo
#define FIFO_IN_COMPONENT_NAME fifo_in
#define FIFO_IN_BASE 0x20080
#define FIFO_IN_SPAN 16
#define FIFO_IN_END 0x2008f

/*
 * Macros for device 'fifo_out', class 'altera_avalon_sc_fifo'
 * The macros are prefixed with 'FIFO_OUT_'.
 * The prefix is the slave descriptor.
 */
#define FIFO_OUT_COMPONENT_TYPE altera_avalon_sc_fifo
#define FIFO_OUT_COMPONENT_NAME fifo_out
#define FIFO_OUT_BASE 0x20090
#define FIFO_OUT_SPAN 16
#define FIFO_OUT_END 0x2009f


#endif /* _ALTERA_HPS_DEF_H_ */
